"""
Property-based testing of the axioms with `Hypothesis
<https://hypothesis.readthedocs.io>`_.

An :class:`Axiom` is an equation stated once on a :class:`Testable`
class — an abstract base class of :mod:`discopy.abc`, whether a category
or the serialisation interface — and inherited by every class below it,
where
:meth:`Axiom.failing` and :meth:`Axiom.inapplicable` classify it when a
class breaks it or has no such structure. A class that implements
:meth:`Testable.strategy` generates its own terms; one that cannot do so
yet leaves the strategy to raise. The matrix in ``proptest/`` reads the
types it quantifies over off :meth:`Testable.subclasses` rather than a
list, and checks every axiom of every type against generated arguments,
one cell per pair; CONTRIBUTING.md says how to run it.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Equation
    Axiom
    AxiomFailure
    Rule
    Testable
    PatternBase
    ItemBase
    Var
    Derived
    Adjoint
    Delay
    Exp
    Word
    Alternatives
    Sequent
    Hom
    Signature
    Kind
    Atom
    NonEmpty
    Pair
    Subspace
    Serialisable

.. admonition:: Functions

    .. autosummary::
        :template: function.rst
        :nosignatures:
        :toctree:

        axiom
        rule
        leaf
        search
        resolve
        assert_axioms
        assert_strategy_finds

Search strategies as proof search
---------------------------------

A category presented by generators and structural rules is a deductive
system: an object is a sequent ``dom ⊢ cod``, an arrow is a proof, a layer
is a rule application. Generating an arrow with both boundaries fixed —
what every law of a square, a trace or a feedback loop needs — is type
inhabitation in that system, and :func:`search` does it literally, as
backward proof search: from a sequent and a ``size``, the number of boxes
left to place, draw one of the :class:`Rule` that apply, recurse on its
premises, conclude. Every choice is a Hypothesis draw, so Hypothesis's
own search — random generation, shrinking, the example database — is the
control strategy of the proof search, and the category's rules are its
proof system.

The rules are stated once on the abstract base classes of
:mod:`discopy.abc`, beside the axioms that exercise the structure they
generate, and collected through the same walk, :meth:`Testable.declarations`,
so a category generates exactly the structures whose laws it must satisfy.
``Category`` states ``identity`` (``x ⊢ x`` with no box), ``box`` (any
sequent with one box, a fresh generator) and ``cut`` (a drawn middle
boundary, two premises); ``MonoidalCategory`` adds ``tensoring``, a split
of both boundaries whose box-less side is a whiskering; each level then
adds the leaf for its own structure — ``braiding`` on ``x @ y ⊢ y @ x``,
``cupping`` on ``x @ x.r ⊢ ()``, ``copying`` on ``x ⊢ x @ x`` — or a rule
with a premise, ``tracing`` and ``feeding_back``, whose premise is the
sequent extended by a drawn atom of memory. A level drops an inherited
rule by assignment, as for axioms: ``CompactCategory.twisting`` is
:meth:`Rule.inapplicable`. Only the generator class of a level generates
fresh boxes on its own: a structural box such as a cup is generated by the
rules of its category, inside a diagram.

Three facts about this search:

- **It never dead-ends and never filters.** With ``size >= 1`` the
  ``box`` rule always applies; a side that ``tensoring`` gives no box is a
  common prefix or suffix of the boundaries, hence an identity; a
  structural leaf is offered only when its pattern matches. In the
  language of focusing :cite:`Andreoli92`, the invertible rules —
  identity, whiskering, cut through a fresh middle — apply freely and the
  non-invertible ones are pattern-matched. Inhabitation is trivial here
  because the signature is open: a fresh box closes any hole. Deciding
  *equality* of the generated terms is the hard part — unknot-hard for
  braided categories :cite:`DelpeuchVicary21` — and that is the business
  of each level's ``equation_factory``, not of the generator. Fixing the
  signature first would make inhabitation the parsing problem, NP-complete
  for multiplicative linear logic :cite:`LincolnEtAl92` and the Lambek
  calculus :cite:`Pentus06`; a generator never needs to solve it, since it
  draws the derivation and reads the lexicon off its leaves
  :cite:`PalkaEtAl11,LampropoulosEtAl18`.
- **It is complete for the distribution that matters.** Any diagram of
  two layers or more is a cut at a layer boundary and a layer is a tensor
  of boxes and identities, so every diagram between ``dom`` and ``cod`` has
  a derivation, and the size bound is the only knob. A structural leaf
  needs a boundary of a particular shape, which a random type rarely
  takes; the leaf declares that shape with :meth:`Rule.hint`, given the
  sequent, and ``cut`` draws its middle from the hints as well as from the
  types.
- **It shows in the statistics.** Every rule application is a Hypothesis
  ``event``, so ``--hypothesis-show-statistics`` lists how often each rule
  fired in a cell, the input of a strategy audit; and a shrunk
  counterexample is a minimal derivation, since deleting a cut collapses
  the term to a leaf.

Rules and the arguments of a law share one sequent-pattern language,
:data:`Pattern`, closed under a :class:`PatternBase`. A :class:`Var`
stands for a type, an atom, a pair of atoms or a non-empty type, an
:class:`Adjoint`, a :class:`Delay` or an :class:`Exp` for what is derived
from one, and ``@`` concatenates them into a :class:`Word` for one
boundary of a :class:`Sequent`, ``|`` joining :class:`Alternatives`. A
pattern matches a value by binding its metavariables and generates one
by drawing the unbound ones by kind, so it is a :class:`Testable` of the
values it stands for. A leaf reads the sequent it concludes off the
annotations of its ``dom`` and ``cod``, ``cupping[X: Atom[C0]](cls, dom:
X @ X.r, cod: (), X)``, and a rule its conclusion and the named sequents
of its premises, ``tracing_left[A: C0, B: C0, M: Atom[C0]](cls, dom: A,
cod: B, f: C1[M @ A, M @ B])``, the metavariables being the type
parameters and their :class:`Kind` the bound: matching the conclusion
binds the variables, the unbound ones are drawn by kind, and the hint a
cut draws its middle from is derived from the conclusion, matched on
either boundary of the sequent, in any window when its length is fixed,
so that the rule fires on one side of the cut. A law states the sequents
of its arguments the same way, ``bifunctoriality[A: C0, B: C0, C: C0,
D: C0, U: C0, V: C0](cls, f: C1[A, B], g: C1[C, D], h: C1[B, U], k:
C1[D, V])``, an object by its kind, ``hexagon_left[X: Atom[C0], Y:
Atom[C0], Z: Atom[C0]](cls, x: X, y: Y, z: Z)``: its
:attr:`Axiom.pattern` is the :class:`Signature` of its annotations,
whose strategy draws the metavariables once and each arrow through the
search of its sequent, and :meth:`Axiom.strategy` maps it to the
equations the law states, so nothing is declared beside the law. A law
compared modulo a normal form is :meth:`Axiom.weaken`ed to
:func:`connected` equations, where the normal form is defined. Identity,
box, cut, tensoring and permuting, which split or shuffle arbitrarily,
stay procedural.

The search does not focus the syntax: focused proofs are canonical forms,
and a generator of normal forms would make the interchange, naturality and
sliding laws vacuous. Uniform sampling of large typed terms is a different
problem, solved by Boltzmann samplers :cite:`BendkowskiEtAl18`; the matrix
wants small, shrinkable, structurally diverse terms, which size-indexed
random backward search gives.

Adding a structure to a level means declaring its :class:`Rule` beside its
abstract method — a :func:`leaf` for a box the boundary determines, a
:func:`rule` for one with premises, with a :meth:`Rule.hint` when its
boundary is a shape a random type rarely takes — and pinning the reach in
the module's ``test_strategy`` with :func:`assert_strategy_finds`, inside a
hole with both boundaries fixed where a law needs it there.
"""

from __future__ import annotations

import __future__
import inspect
import pickle
import sys
from collections.abc import Callable, Iterator
from copy import deepcopy
from dataclasses import KW_ONLY, dataclass, field, replace
from functools import cache, wraps
from typing import TYPE_CHECKING, ClassVar, Concatenate, Self, TypeVar

from discopy.utils import (
    AxiomError,
    NamedGeneric,
    classproperty,
    factory_name,
)

if TYPE_CHECKING:
    from hypothesis import strategies as st


C0 = TypeVar("C0")
C1 = TypeVar("C1")
"""
The object and arrow types of the category an axiom is bound to.

An axiom annotates its arguments with these rather than with the concrete
types of the module it is written in, so that a subclass inherits the
override with its own types: :meth:`Axiom.strategy` rebinds both names to
``category.ob`` and ``category.ar``, and :data:`typing.Self` to the category
itself for a law of every term of a type whatever its level, such as
:meth:`Serialisable.repr_transparency`, in its :attr:`Axiom.scope` when it
evaluates the annotations; a law of functors names the category they map
from as ``Self.dom``. This is also why every module stating an axiom
needs ``from __future__ import annotations``, which keeps them
unevaluated: :class:`Axiom` refuses an equation compiled without it.
Rebinding happens through the ``locals`` of that evaluation because the
:pep:`695` type parameters of :class:`discopy.abc.Category` live in a
scope :func:`eval` cannot see, in globals or anywhere else.
"""


GENERATORS = tuple("abcde")
"""
The names the generators of a free category are drawn from.

They are finitely many and shared, so a generated functor can name every one
of them: composing two functors keeps only the keys of the left-hand map, so
a functor that named just a few would compose to one defined nowhere else.
"""


class Equation(NamedGeneric["ar"]):
    """
    An equation is a list of ``terms`` to be compared up to a function
    ``up_to``, the identity by default.  Casting it to ``bool`` checks
    whether its terms are all equal up to that function.

    Parameters:
        terms : The terms of the equation.
        symbol : The symbol between each pair of terms, ``"="`` by default.
        symbols : The symbols between each pair of terms, overriding
            ``symbol``; ``len(terms) * (symbol, )`` by default.
        up_to : The function up to which ``bool(equation)`` compares its
            terms, overriding the subclass' :attr:`up_to` if given.

    Example
    -------
    The number of boxes inside an arrow is left unchanged by associativity,
    so we can compare arrows up to the function that counts them modulo 2:

    >>> from discopy.cat import Ob, Box, Equation
    >>> x = Ob('x')
    >>> f, g = Box('f', x, x), Box('g', x, x)
    >>> parity = lambda term: len(term.inside) % 2
    >>> assert not Equation(f, f >> g >> g)
    >>> assert Equation(f, f >> g >> g, up_to=parity)
    """
    up_to = None

    def __init__(self, *terms, symbol="=", symbols=None, up_to=None):
        self.terms = terms
        self.symbols = tuple(symbols) if symbols is not None\
            else len(terms) * (symbol, )
        if up_to is not None:
            self.up_to = up_to

    def modulo(self, up_to: Callable) -> Equation:
        """
        The same equation compared up to the given function, rebinding
        :attr:`up_to`, whose name the attribute already takes.

        >>> from discopy.cat import Ob, Box, Equation
        >>> x = Ob('x')
        >>> f, g = Box('f', x, x), Box('g', x, x)
        >>> assert Equation(f >> g, g >> f).modulo(lambda _: True)
        """
        return type(self)(*self.terms, symbols=self.symbols, up_to=up_to)

    def __repr__(self):
        """
        >>> from discopy.cat import Ob, Box, Equation
        >>> Equation(Box('f', Ob('x'), Ob('x')))
        cat.Equation(cat.Box('f', cat.Ob('x'), cat.Ob('x')))
        """
        return factory_name(type(self))\
            + f"({', '.join(map(repr, self.terms))})"

    def __str__(self):
        return f"Equation({', '.join(map(str, self.terms))})"

    def __bool__(self):
        terms = self.terms if self.up_to is None\
            else list(map(self.up_to, self.terms))
        return all(term == terms[0] for term in terms)


class AxiomFailure(AxiomError):
    """
    A law declared broken, raised when the bound axiom is called: the
    reason is the message and :attr:`equation` is the law evaluated on the
    arguments, whose sides say how it failed.
    """

    def __init__(self, reason: str, equation):
        super().__init__(reason, equation)
        self.equation = equation


class Testable[T]:
    """
    A testable class states axioms, which its subclasses inherit along
    with the structure they axiomatise, and says how to generate the
    terms those axioms quantify over.

    Both kinds of law meet here: a :class:`discopy.abc.Category` states
    those of a categorical structure, a :class:`Serialisable` those of
    writing a term down and reading it back. A class need not be a
    category to state laws, which is why the two meet here rather than in
    either of them. Nor need a testable be a class of terms: an
    :class:`Axiom` generates the equations it states and a pattern of the
    :data:`Pattern` language the values it stands for, each implementing
    :meth:`strategy` on the instance rather than the class.

    A type that implements :meth:`strategy` is one the property matrix
    in ``proptest/`` quantifies over, checking each of its axioms against
    generated terms. One that does not is not checked, and says so by
    leaving :meth:`strategy` to raise.
    """

    @classmethod
    def strategy(cls, **params) -> st.SearchStrategy[T]:
        """
        Build a `search strategy
        <https://hypothesis.readthedocs.io/en/latest/data.html>`_ for
        instances of ``cls``, which is how a class enrols itself in the
        property matrix.

        An override that delegates to another strategy accepts
        ``**params``, pops the parameters it consumes and forwards the
        rest, so that a caller's bounds pass through unchanged and a
        subclass overrides what a base popped just by passing it. A
        terminal strategy instead declares exactly the parameters it
        implements: a constraint it cannot honour fails loudly as an
        unexpected keyword rather than being silently dropped.

        The default raises: a class states its laws as soon as it has
        them, and is checked against them once it says how to draw their
        terms. It is deliberately not an :func:`abc.abstractmethod`,
        which would make every category that has not implemented one
        uninstantiable rather than merely unchecked.

        >>> from discopy.monoidal import Layer
        >>> Layer.strategy()
        Traceback (most recent call last):
         ...
        NotImplementedError: No search strategy implemented for Layer
        """
        raise NotImplementedError(
            f"No search strategy implemented for {cls.__name__}")

    @classmethod
    def declarations(cls, kind: type) -> dict:
        """
        The declarations of a kind inherited by ``cls``, keyed by name and
        bound to ``cls``, an override on a subclass hiding the base it
        overrides.

        Names are collected before they are filtered, so that assigning
        anything that is not of the kind over an inherited declaration drops
        it altogether, rather than restating it.
        """
        visible = {
            name: value
            for base in reversed(cls.__mro__)
            for name, value in base.__dict__.items()}
        return {name: value.bind(cls) for name, value in visible.items()
                if isinstance(value, kind)}

    @classproperty
    def axioms(cls) -> dict[str, Axiom]:
        """ The axioms inherited by ``cls``, see :meth:`declarations`. """
        return cls.declarations(Axiom)

    @classmethod
    def subclasses(cls) -> tuple[type[Testable], ...]:
        """
        Every transitive subclass of ``cls``, ``cls`` itself included.

        A subclass is listed once, however many paths reach it, in the
        order a breadth-first walk of the subclass graph first meets
        it.

        Example
        -------
        >>> from discopy.cat import Arrow, Box
        >>> assert Arrow.subclasses()[0] is Arrow
        >>> assert Box in Arrow.subclasses()  # a subclass of a subclass
        """
        found, queue = {cls: None}, [cls]
        while queue:
            for subclass in queue.pop(0).__subclasses__():
                if subclass not in found:
                    found[subclass] = None
                    queue.append(subclass)
        return tuple(found)


no_strategy = Testable.__dict__["strategy"]
"""
The default :meth:`Testable.strategy`, under a name that can be assigned.

A class inherits it from :class:`Testable` unless a base it refines
implements one: the terms of a :class:`discopy.monoidal.Ty` are not
those of the :class:`discopy.cat.Ob` it subclasses, so a class that
would inherit the wrong strategy declares ``strategy = no_strategy``
until it implements its own.
"""


@dataclass
class Axiom[**P, T](Testable[Equation]):
    """
    An axiom of a category, stated once on an abstract base class and
    inherited by every category below it.

    The category is the class the axiom is bound to, e.g.
    :class:`discopy.cat.Arrow` for the axioms of
    :class:`discopy.abc.Category`. The axiom is a classmethod of it,
    implicitly: its first parameter is the category and the remaining ones
    are generated from their annotations — an object for the typing of
    identities, three composable arrows for the associativity of
    composition, a term of the category itself for
    :meth:`Serialisable.repr_transparency`. The :attr:`pattern` of those
    annotations is the input of the law and :meth:`strategy`, which maps
    it to the equations the law states, its output: a bound axiom is a
    :class:`Testable` whose terms are its equations.

    Calling a bound axiom returns its own verdict: :obj:`NotImplemented`
    when the structure does not apply to the category, and the equation
    itself otherwise; a law declared broken raises an
    :class:`AxiomFailure` carrying that equation instead of returning it.

    A law is broken when *some* argument is a counterexample, not every one,
    so :attr:`broken` is declared by :meth:`failing` before any argument is
    generated — the property matrix marks such an axiom as an expected
    failure and lets the search find the counterexample.

    Parameters:
        equation : The function stating the law, from the category and the
            arguments annotated with :obj:`C0`, :obj:`C1`,
            :data:`typing.Self` or a :class:`Testable` to an
            :class:`Equation`, or to :obj:`NotImplemented` when the
            structure does not apply.
        category : The class the axiom is bound to, :obj:`None` until
            :meth:`bind` or the attribute access on a class binds it.
        name : The attribute the law is stored under, the name of the
            equation by default.
        subspace : The predicate on the equation the law is quantified
            over, declared by :meth:`weaken`, :obj:`None` for the whole
            space.
        broken : Whether the law is declared broken by :meth:`failing`.
    """

    equation: Callable[Concatenate[type[T], P], Equation]
    _: KW_ONLY
    category: type[T] = None
    name: str = None
    subspace: Callable = None
    broken: bool = False

    def __post_init__(self):
        function = inspect.unwrap(self.equation)
        deferred = __future__.annotations.compiler_flag
        if not function.__code__.co_flags & deferred:
            raise TypeError(
                f"{function.__module__} states the axiom {function.__name__} "
                "without `from __future__ import annotations`.")
        self.name = self.name or self.equation.__name__
        self.__doc__ = self.equation.__doc__

    def __repr__(self):
        """
        A bound axiom is the attribute of its category, e.g.
        ``cat.Arrow.unitality``; an unbound one wraps a function and has no
        transparent representation.
        """
        if self.category is None:
            return f"{type(self).__name__}({self.name})"
        return f"{factory_name(self.category)}.{self.name}"

    def __hash__(self):
        return hash((self.equation, self.category, self.name))

    def bind(self, category: type[T]) -> Axiom[P, T]:
        """ Bind the axiom to a concrete category. """
        return replace(self, category=category)

    def __get__(self, instance, owner: type[T]) -> Axiom[P, T]:
        return self.bind(owner)

    def modulo(self, up_to) -> Axiom[P, T]:
        """
        The same law with its equation compared up to a function, so that a
        category weakens an inherited axiom in one statement, e.g. a diagram
        compares the interchange law up to its normal form:
        ``Diagram.bifunctoriality = MonoidalCategory.bifunctoriality.modulo(
        Diagram.normal_form)``.
        """
        @wraps(self.equation)
        def equation(*args, **kwargs):
            return self.equation(*args, **kwargs).modulo(up_to)
        return replace(self, equation=equation)

    def failing(self, reason: str) -> Axiom[P, T]:
        """
        The same law declared broken: calling it raises an
        :class:`AxiomFailure` with the reason as message and the equation
        evaluated on the arguments, e.g. ``braid_naturality =
        BraidedCategory.braid_naturality.failing("A free braid is a box.")``.
        """
        @wraps(self.equation)
        def equation(*args, **kwargs):
            raise AxiomFailure(reason, self.equation(*args, **kwargs))
        equation.__doc__ = reason
        return replace(self, equation=equation, broken=True)

    def inapplicable(self, reason: str) -> Axiom[P, T]:
        """
        The same law declared not to apply to the category: it takes no
        argument and returns :obj:`NotImplemented`, with the reason as its
        documentation, e.g. ``trace_vanishing =
        TracedCategory.trace_vanishing.inapplicable("No trace.")``.
        """
        def law(cls):
            return NotImplemented
        law.__doc__ = reason
        return replace(self, equation=law, subspace=None, broken=False)

    def weaken(self, subspace: Callable) -> Axiom[P, T]:
        """
        The same law quantified over the subspace where a predicate on
        its equation holds, e.g. ``bifunctoriality =
        MonoidalCategory.bifunctoriality.modulo(normal_form).weaken(
        connected)`` for the interchange compared up to a normal form
        defined on connected diagrams only. A :class:`Subspace` also
        carries the parameters the category draws inside it with, so
        that an argument outside it is not drawn only to be rejected.
        """
        return replace(self, subspace=subspace)

    @property
    def parameters(self) -> tuple[inspect.Parameter, ...]:
        """
        The parameters whose arguments the property matrix generates: all
        but the first, which is the category.
        """
        return tuple(
            inspect.signature(self.equation).parameters.values())[1:]

    @property
    def scope(self) -> dict:
        """
        What the names in the annotations of the axiom stand for: the
        category itself for :data:`typing.Self`, its objects for :obj:`C0`
        and, for :obj:`C1`, the :class:`Hom` of its arrows, which
        subscripts into a :class:`Sequent`: ``f: C1[A, B]`` is an arrow
        from what ``A`` stands for to what ``B`` stands for, the law's
        type parameters standing for metavariables of the :class:`Kind`
        their bound gives. A monoid,
        having no objects of its own, stands for both; a class of functors
        is the arrows of ``Cat``, and the category it maps from is
        reachable as ``Self.dom``.
        """
        return dict(
            metavariables(inspect.unwrap(self.equation)),
            Self=self.category,
            C0=getattr(self.category, "ob", self.category),
            C1=Hom(getattr(self.category, "ar", self.category)))

    def annotations(self) -> dict:
        """ The evaluated annotation of each generated parameter. """
        if self.category is None:
            raise TypeError(f"{self.name} is not bound to a class.")
        namespace = inspect.unwrap(self.equation).__globals__
        return {
            parameter.name: eval(parameter.annotation, namespace, self.scope)
            if isinstance(parameter.annotation, str) else parameter.annotation
            for parameter in self.parameters
            if parameter.default is inspect.Parameter.empty}

    @property
    def pattern(self) -> Signature:
        """
        The pattern of the arguments the bound axiom expects, one per
        required parameter, from its annotation evaluated in the
        :attr:`scope` of the category: the :class:`Sequent` ``C1[A, B]``
        for an arrow drawn through the search, a :class:`Var` for an
        object of its kind and the :class:`Hom` of any :class:`Testable`
        for a term drawn from its own strategy. Its strategy is the input
        of the law, see :class:`Signature`.

        Only the parameters' annotations are evaluated: the law's return
        annotation may name a type its module imports for checking only.
        """
        return Signature({
            name: annotation if isinstance(annotation, PatternBase)
            else Hom(annotation)
            for name, annotation in self.annotations().items()})

    def equations(self, evaluate: Callable) -> st.SearchStrategy[Equation[T]]:
        """
        The law evaluated by a function of its arguments, on those its
        :attr:`pattern` draws inside the subspace of a :meth:`weaken`ed
        law: the category draws with the parameters of the subspace, and
        the equations its predicate rejects are filtered out.
        """
        params = getattr(self.subspace, "params", None) or {}
        drawn = self.pattern.strategy(self.category, **params).map(
            lambda args: evaluate(*args))
        return drawn if self.subspace is None else drawn.filter(self.subspace)

    def strategy(self) -> st.SearchStrategy[Equation[T]]:
        """
        Generate the equations the bound axiom states, the terms it is
        checked on: a law declared broken raises its :class:`AxiomFailure`
        from the draw, as it does from a call.
        """
        return self.equations(self)

    def falsify(self, **params) -> Equation[T]:
        """
        Search for a shrunk counterexample to the bound axiom: an equation
        of the law that is false, the one a law declared broken raises
        included, raising :class:`hypothesis.errors.NoSuchExample` when no
        counterexample is found. Keyword arguments are passed to
        :func:`hypothesis.find`.

        >>> from discopy.cat import Arrow
        >>> Arrow.associativity.falsify()  # doctest: +ELLIPSIS
        Traceback (most recent call last):
         ...
        hypothesis.errors.NoSuchExample: No examples found of condition ...
        """
        from hypothesis import find

        def verdict(*args):
            try:
                return self(*args)
            except AxiomFailure as failure:
                return failure.equation

        return find(
            self.equations(verdict), lambda equation: not equation, **params)

    def canonical(self) -> Equation[T]:
        """
        The law as a schema: its equation on the canonical arguments of
        its :attr:`pattern`, each metavariable an object named after it
        and each arrow a box named after its parameter, the equation a
        law declared broken raises included.

        >>> from discopy.cat import Arrow
        >>> print(Arrow.associativity.canonical())
        Equation(f >> g >> h, f >> g >> h)
        """
        try:
            return self(*self.pattern.canonical(self.category))
        except AxiomFailure as failure:
            return failure.equation

    def draw(self, **params):
        """
        Draw the :meth:`canonical` equation of the law, the parameters
        those of :meth:`discopy.monoidal.Equation.draw`.

        >>> from discopy.symmetric import Diagram
        >>> Diagram.bifunctoriality.draw(
        ...     doctest="docs/_static/axioms/bifunctoriality.svg")

        .. image:: /_static/axioms/bifunctoriality.svg
            :align: center
        """
        equation = self.canonical()
        if equation is NotImplemented:
            raise TypeError(f"{self} does not apply, so has nothing to draw.")
        return equation.draw(**params)

    def arguments(self, *args: P.args, **kwargs: P.kwargs) -> dict:
        """ Bind the arguments to the :attr:`parameters` of the axiom. """
        if self.category is None:
            raise TypeError(f"{self.name} is not bound to a class.")
        bound = inspect.Signature(self.parameters).bind(*args, **kwargs)
        bound.apply_defaults()
        return dict(bound.arguments)

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> Equation[T]:
        return self.equation(self.category, **self.arguments(*args, **kwargs))


def axiom[**P, T](
        equation: Callable[Concatenate[type[T], P], Equation]) -> Axiom[P, T]:
    """
    Decorate an equation as a categorical axiom: a classmethod of its
    category, implicitly, whose remaining parameters are generated.
    """
    return Axiom(equation)


@dataclass
class Rule[T]:
    """
    An inference rule of a category seen as a deductive system: a sequent
    is a pair of objects ``dom ⊢ cod`` with a ``size``, the number of boxes
    left to place, and the rule says whether it :attr:`applies` to the
    sequent and, if chosen, which :attr:`premises` it reduces it to and how
    to conclude the arrow from their proofs. A rule is stated once on an
    abstract base class beside the axioms that exercise the structure it
    generates, and :func:`search` interprets the rules a category inherits.

    Parameters:
        premises : From the category, a Hypothesis ``draw``, the sequent and
            the strategy for ``types``, to the list of premises
            ``(dom, cod, size)`` and the function concluding the arrow from
            their proofs; the draws it makes are those of the rule chosen.
        applies : Whether the rule applies to the sequent, without drawing.
        shape : A strategy for boundaries the rule fires on, given the
            category, the sequent and the strategy for types, declared by
            :meth:`hint` and drawn as a middle boundary by ``Category.cut``.
        category : The class the rule is bound to, :obj:`None` until
            :meth:`bind` or the attribute access on a class binds it.
        name : The attribute the rule is stored under.
    """

    premises: Callable
    applies: Callable
    _: KW_ONLY
    shape: Callable = None
    category: type[T] = None
    name: str = None

    def __post_init__(self):
        self.name = self.name or self.premises.__name__
        self.__doc__ = self.premises.__doc__

    def __repr__(self):
        if self.category is None:
            return f"{type(self).__name__}({self.name})"
        return f"{factory_name(self.category)}.{self.name}"

    def bind(self, category: type[T]) -> Rule[T]:
        """ Bind the rule to a concrete category. """
        return replace(self, category=category)

    def __get__(self, instance, owner: type[T]) -> Rule[T]:
        return self.bind(owner)

    def hint(self, shape: Callable) -> Rule[T]:
        """
        The same rule declaring a strategy for boundaries it fires on, so
        that a cut can draw a middle boundary the rule applies to, e.g.
        ``x @ x.r`` for a cup.
        """
        return replace(self, shape=shape)

    def inapplicable(self, reason: str) -> Rule[T]:
        """
        The same rule declared never to apply to the category, with the
        reason as its documentation, e.g. ``twisting =
        BalancedCategory.twisting.inapplicable("The twist is the identity.")``.
        """
        never = replace(
            self, applies=lambda cls, dom, cod, size: False, shape=None)
        never.__doc__ = reason
        return never


def declared(function) -> tuple[Sequent, dict[str, Sequent]]:
    """
    What a rule declares in its annotations, evaluated with its type
    parameters as metavariables: the :class:`Sequent` it concludes from
    ``dom`` and ``cod``, and the sequent of each premise, by name.
    """
    variables = metavariables(function)
    scope = dict(variables, C1=Hom())
    evaluated = {
        parameter.name: eval(
            parameter.annotation, function.__globals__, scope)
        if isinstance(parameter.annotation, str) else parameter.annotation
        for parameter in inspect.signature(function).parameters.values()
        if parameter.annotation is not inspect.Parameter.empty}
    conclusion = Sequent(
        boundary(evaluated.pop("dom", ())), boundary(evaluated.pop("cod", ())))
    premises = {
        name: annotation for name, annotation in evaluated.items()
        if isinstance(annotation, Sequent)}
    return conclusion, premises


def windows(word: Word, typ):
    """
    The matches of a word against a type or, when it has a fixed
    length, against each window of the type, as triples of the context on
    the left, the environment and the context on the right.
    """
    if not word.fixed or not hasattr(typ, "__len__"):
        for env in word.match(typ):
            yield None, env, None
        return
    for start in range(size(typ) - word.length + 1):
        stop = start + word.length
        for env in word.match(typ[start:stop]):
            yield typ[:start], env, typ[stop:]


def hint_from(sequents: list[Sequent]) -> Callable:
    """
    The boundary strategy a rule derives from the sequents it concludes:
    a middle that a domain pattern matches on the sequent's domain, or
    a codomain pattern on the codomain, so that the rule fires on one
    side of the cut, and otherwise a fresh instance of either pattern.
    """
    def shape(cls, dom, cod, types):
        from hypothesis import strategies as st

        def around(left, right):
            return lambda middle: middle if left is None\
                else left @ middle @ right

        options = []
        for sequent in sequents:
            for dom_pattern, cod_pattern in sequent.options:
                for source, target, side in (
                        (dom_pattern, cod_pattern, dom),
                        (cod_pattern, dom_pattern, cod)):
                    for left, env, right in windows(source, side):
                        options.append(
                            target.strategy(cls, env).map(around(left, right)))
                options += [
                    word.strategy(cls) for word in (dom_pattern, cod_pattern)
                    if word.vars and not all(
                        var.kind == "type" for var in word.vars)]
        return st.one_of(*options) if options else st.nothing()

    return shape


def leaf[T](*args) -> Rule[T] | Callable[[Callable], Rule[T]]:
    """
    Decorate a leaf rule: bare, it reads the sequent it concludes off the
    annotations of ``dom`` and ``cod``, its metavariables being its type
    parameters, e.g. ``def cupping[X: Atom[C0]](cls, dom: X @ X.r, cod:
    (), X)``; given :class:`Sequent` patterns instead, it concludes any
    of them. The function builds a single box from the category, the
    sequent and the bound variables, and the rule applies to sequents of
    size one that some pattern matches.
    """
    if len(args) == 1 and callable(args[0]):
        conclusion, _ = declared(args[0])
        return leaf(conclusion)(args[0])
    conclusions = list(args)

    def decorate(build):
        def applies(cls, dom, cod, size):
            return size == 1 and any(
                True for sequent in conclusions
                for _ in sequent.matches(dom, cod))

        def premises(cls, draw, dom, cod, size, types):
            env = next(
                env for sequent in conclusions
                for env in sequent.matches(dom, cod))
            return [], lambda: build(cls, dom, cod, **env)

        premises.__name__, premises.__doc__ = build.__name__, build.__doc__
        return Rule(premises, applies, shape=hint_from(conclusions))

    return decorate


def rule[T](
        build: Callable = None, *, applies: Callable = None,
        boxes: int = 1) -> Rule[T] | Callable[[Callable], Rule[T]]:
    """
    Decorate an inference rule: bare, it reads the sequent it concludes
    off the annotations of ``dom`` and ``cod`` and its premises off the
    other annotated parameters, its metavariables being its type
    parameters, e.g. ``def tracing_left[A: C0, B: C0, M: Atom[C0]](cls,
    dom: A, cod: B, f: C1[M @ A, M @ B], **env)``, the function concluding
    from the bound variables and the proofs of the premises and counting
    the ``boxes`` it adds itself. Given ``applies``, the predicate saying
    when a rule applies, the function gives its premises instead, e.g.
    ``@rule(applies=lambda cls, dom, cod, size: size >= 2)`` for a cut.
    """
    if applies is not None:
        return lambda premises: Rule(premises, applies)
    if build is None:
        return lambda build: rule(build, boxes=boxes)
    conclusion, premises = declared(build)
    names = tuple(premises)
    variables = tuple({
        var.name: var for sequent in premises.values()
        for var in sequent.vars}.values())

    def applies_to(cls, dom, cod, size):
        return size >= boxes + len(names)\
            and any(True for _ in conclusion.matches(dom, cod))

    def derive(cls, draw, dom, cod, size, types):
        from hypothesis import strategies as st

        env = bind_vars(
            draw, variables, cls, next(conclusion.matches(dom, cod)))
        unit = unit_of(cls, env)
        sizes, left = [], size - boxes
        for remaining in reversed(range(len(names))):
            sizes.append(draw(st.integers(
                min_value=1, max_value=left - remaining)))
            left -= sizes[-1]
        drawn = [
            (*premises[name].instantiate(env, unit), n)
            for name, n in zip(names, sizes)]
        return drawn, lambda *proofs: build(
            cls, dom, cod, **env, **dict(zip(names, proofs)))

    derive.__name__, derive.__doc__ = build.__name__, build.__doc__
    return Rule(derive, applies_to, shape=hint_from([conclusion]))


def search(
        category, *, types, dom=None, cod=None,
        min_leaves=None, max_leaves) -> st.SearchStrategy:
    """
    Generate arrows of the category by backward proof search over its
    rules: from a sequent ``dom ⊢ cod`` with a ``size`` — the number of
    boxes left to place, drawn within the given bounds — draw a rule among
    those that apply, recurse on its premises and conclude. A boundary
    left :obj:`None` is drawn from ``types``, equal to the other one when no
    box may bridge them. Each application is reported as a Hypothesis
    event, so the statistics of a cell say how often each rule fired.
    """
    from hypothesis import event
    from hypothesis import strategies as st

    @st.composite
    def derive(draw, dom, cod, size):
        applicable = [
            rule for rule in category.rules.values()
            if rule.applies(category, dom, cod, size)]
        chosen = draw(st.sampled_from(applicable))
        event(f"rule: {chosen.name}")
        premises, conclude = chosen.premises(
            category, draw, dom, cod, size, types)
        term = conclude(*[draw(derive(*premise)) for premise in premises])
        if (term.dom, term.cod) != (dom, cod):
            raise AxiomError(
                f"{chosen} built {term} for {dom} ⊢ {cod}.")
        return term

    @st.composite
    def arrows(draw):
        source = draw(types) if dom is None else dom
        target = cod if cod is not None\
            else source if not max_leaves else draw(types)
        source = target if dom is None and not max_leaves else source
        size = draw(st.integers(
            min_value=max(min_leaves or 0, int(source != target)),
            max_value=max_leaves))
        return draw(derive(source, target, size))

    return arrows()


class PatternBase[T](Testable[T]):
    """
    The base of the :data:`Pattern` language: a pattern stands for values
    of type ``T`` up to the metavariables in it, which it binds by
    :meth:`match`\\ ing a value and reads to :meth:`instantiate` one, and
    its :meth:`strategy` draws the unbound ones by kind, so that a law or
    a rule states the shape of its arguments once and both matching and
    generating follow. ``@`` concatenates patterns into a :class:`Word`
    and ``|`` joins them into :class:`Alternatives`.
    """

    @property
    def vars(self) -> tuple[Var, ...]:
        """ The metavariables of the pattern, in order of first occurrence. """
        raise NotImplementedError

    def match(self, value, env: dict = None) -> Iterator[dict]:
        """
        Yield every environment binding the variables so that the pattern
        stands for ``value``, extending ``env``: a type variable may take
        any length, so there may be several, or none.
        """
        raise NotImplementedError

    def instantiate(self, env: dict, unit=None) -> T:
        """ The value the pattern stands for, given all its variables. """
        raise NotImplementedError

    def generate(self, draw: Callable, factory, env: dict, **params) -> T:
        """
        Draw a value the pattern stands for, extending ``env`` with the
        variables it draws from the ``factory`` by kind; the parameters go
        to the strategies of the factory's terms.
        """
        bound = bind_vars(draw, self.vars, factory, env)
        return self.instantiate(bound, unit_of(factory, bound))

    def strategy(
            self, factory, env: dict = None, **params) -> st.SearchStrategy[T]:
        """
        A strategy for the values the pattern stands for, the variables
        not in ``env`` drawn from the ``factory``: the category whose
        objects and arrows they stand for.
        """
        return generated()(self, factory, dict(env or {}), params)

    def canonical(self, factory, env: dict = None, name: str = None) -> T:
        """
        The value the pattern stands for by default: each variable not in
        ``env`` an object of the ``factory`` named after it, an arrow a
        box named ``name``, so that a law reads as a schema, see
        :meth:`Axiom.canonical`.
        """
        bound = canonical_vars(self.vars, factory, env)
        return self.instantiate(bound, unit_of(factory, bound))

    def __matmul__(self, other) -> Word:
        return Word.of(self) @ other

    def __rmatmul__(self, other) -> Word:
        return Word.of(other) @ self

    def __or__(self, other) -> Alternatives:
        return Alternatives.of(self) | other

    def __ror__(self, other) -> Alternatives:
        return Alternatives.of(other) | self


class ItemBase[T](PatternBase[T]):
    """
    The base of the items of a :class:`Word`, see :data:`Item`: a
    metavariable or one derived from it, standing for a slice of a type
    whose length its kind fixes or leaves free.
    """

    @property
    def fixed(self) -> bool:
        """ Whether the length of the item is known before matching. """
        raise NotImplementedError

    @property
    def length(self) -> int:
        """ The length of a :attr:`fixed` item. """
        raise NotImplementedError

    def lengths(self, typ, position: int) -> tuple[int, ...]:
        """ The lengths the item may take from a position of a type on. """
        raise NotImplementedError

    def value(self, env: dict) -> T:
        """ What the item stands for, given the values of its variables. """
        raise NotImplementedError

    def invert(self, value, env: dict) -> dict | None:
        """
        The environment binding the variables so that the item stands for
        ``value``, extending ``env`` consistently, or :obj:`None`.
        """
        raise NotImplementedError

    def match(self, value, env: dict = None) -> Iterator[dict]:
        yield from Word.of(self).match(value, env)

    def instantiate(self, env: dict, unit=None) -> T:
        return self.value(env)

    def bindings(
            self, typ, position: int, env: dict) -> Iterator[tuple[int, dict]]:
        """ The lengths and environments the item can take at a position. """
        if all(var.name in env for var in self.vars):
            value = self.value(env)
            if part(typ, position, position + size(value)) == value:
                yield size(value), env
            return
        for length in self.lengths(typ, position):
            value = part(typ, position, position + length)
            bound = None if value is None else self.invert(value, env)
            if bound is not None:
                yield length, bound


@dataclass(frozen=True)
class Var[T](ItemBase[T]):
    """
    A metavariable, standing for a type, an atom, a pair of atoms or a
    non-empty type according to its ``kind``; ``.r``, ``.l``, ``.d``,
    ``<<`` and ``>>`` derive the adjoints, delay and exponentials of what
    it stands for, see :class:`Adjoint`, :class:`Delay` and :class:`Exp`.

    >>> X, A = Var.atom('X'), Var.type('A')
    >>> print(A @ X @ X.r)
    A @ X @ X.r
    >>> Var.atom('X')
    Var.atom('X')
    """
    name: str
    kind: str = "type"

    LENGTHS: ClassVar[dict] = {
        "atom": (1, ), "pair": (2, ), "type": None, "nonempty": None}

    def __post_init__(self):
        if self.kind not in self.LENGTHS:
            raise ValueError(f"Unknown kind of metavariable: {self.kind!r}.")

    @classmethod
    def type(cls, name: str) -> Var[T]:
        """ A metavariable for any type. """
        return cls(name, "type")

    @classmethod
    def atom(cls, name: str) -> Var[T]:
        """ A metavariable for an atomic type. """
        return cls(name, "atom")

    @classmethod
    def pair(cls, name: str) -> Var[T]:
        """ A metavariable for two atoms. """
        return cls(name, "pair")

    @classmethod
    def nonempty(cls, name: str) -> Var[T]:
        """ A metavariable for a non-empty type. """
        return cls(name, "nonempty")

    def __repr__(self):
        return f"Var.{self.kind}({self.name!r})"

    def __str__(self):
        return self.name

    @property
    def vars(self) -> tuple[Var, ...]:
        return (self, )

    @property
    def fixed(self) -> bool:
        return self.kind in ("atom", "pair")

    @property
    def length(self) -> int:
        return self.LENGTHS[self.kind][0]

    def lengths(self, typ, position: int) -> tuple[int, ...]:
        remaining = size(typ) - position
        if self.kind == "type":
            return tuple(range(remaining + 1))
        if self.kind == "nonempty":
            return tuple(range(1, remaining + 1))
        return tuple(n for n in self.LENGTHS[self.kind] if n <= remaining)

    def value(self, env: dict) -> T:
        return env[self.name]

    def invert(self, value, env: dict) -> dict | None:
        return bind(env, self, value)

    def generate(self, draw: Callable, factory, env: dict, **params) -> T:
        """ What ``env`` binds the variable to, else a draw by kind. """
        if self.name in env:
            return env[self.name]
        if self.kind == "atom":
            return draw(factory.atoms())
        if self.kind == "pair":
            return draw(factory.atoms()) @ draw(factory.atoms())
        if self.kind == "nonempty":
            return draw(factory.ob.strategy(min_length=1))
        return draw(factory.ob.strategy())

    def canonical(self, factory, env: dict = None, name: str = None) -> T:
        """ What ``env`` binds the variable to, else an object of its name. """
        if env and self.name in env:
            return env[self.name]
        if self.kind == "pair":
            return factory.ob(f"{self.name}0") @ factory.ob(f"{self.name}1")
        return factory.ob(self.name)

    r = property(lambda self: Adjoint(self, left=False))
    l = property(lambda self: Adjoint(self, left=True))  # noqa: E741

    def delay(self) -> Delay[T]:
        """ The delay of what the metavariable stands for. """
        return Delay(self)

    d = property(delay)

    def __lshift__(self, other: Var) -> Exp[T]:
        return Exp(self, other, left=True)

    def __rshift__(self, other: Var) -> Exp[T]:
        return Exp(other, self, left=False)


class Kind:
    """
    The kind of a metavariable, as the bound of a type parameter of a law
    or a rule: ``[A: C0]`` stands for a type, ``[X: Atom[C0]]`` for an
    atom, ``[N: NonEmpty[C0]]`` for a non-empty type and ``[P: Pair[C0]]``
    for a pair of atoms.
    """
    kind = "type"

    def __class_getitem__(cls, item):
        return cls


class Atom(Kind):
    """ The kind of an atomic metavariable. """
    kind = "atom"


class NonEmpty(Kind):
    """ The kind of a non-empty metavariable. """
    kind = "nonempty"


class Pair(Kind):
    """ The kind of a metavariable for two atoms. """
    kind = "pair"


def metavariables(function) -> dict[str, Var]:
    """
    The metavariables a function declares as its type parameters, of the
    kind its bound gives, a type when it has none.
    """
    def kind_of(parameter):
        bound = getattr(parameter, "__bound__", None)
        return getattr(bound, "kind", "type")

    return {
        parameter.__name__: Var(parameter.__name__, kind_of(parameter))
        for parameter in getattr(function, "__type_params__", ())}


@dataclass(frozen=True)
class Derived[T](ItemBase[T]):
    """
    An item derived from a metavariable: what it stands for is a function
    of the variable's value, inverted when matching.
    """
    var: Var[T]

    @property
    def vars(self) -> tuple[Var, ...]:
        return self.var.vars

    @property
    def fixed(self) -> bool:
        return self.var.fixed

    @property
    def length(self) -> int:
        return self.var.length

    def lengths(self, typ, position: int) -> tuple[int, ...]:
        return self.var.lengths(typ, position)

    def inverse(self, value):
        """ The variable's value for which the item stands for ``value``. """
        raise NotImplementedError

    def invert(self, value, env: dict) -> dict | None:
        try:
            candidate = self.inverse(value)
        except (ValueError, NotImplementedError, AxiomError):
            return None
        bound = bind(env, self.var, candidate)
        return bound if bound is not None and self.value(bound) == value\
            else None


@dataclass(frozen=True)
class Adjoint[T](Derived[T]):
    """ An adjoint of what a metavariable stands for, ``X.l`` or ``X.r``. """
    left: bool = False

    def __str__(self):
        return f"{self.var}.{'l' if self.left else 'r'}"

    def value(self, env: dict) -> T:
        return getattr(self.var.value(env), "l" if self.left else "r")

    def inverse(self, value):
        return getattr(value, "r" if self.left else "l")


@dataclass(frozen=True)
class Delay[T](Derived[T]):
    """ The delay of what a metavariable stands for, ``P.d``. """

    def __str__(self):
        return f"{self.var}.d"

    def value(self, env: dict) -> T:
        return self.var.value(env).delay()

    def inverse(self, value):
        return value.delay(-1)


@dataclass(frozen=True)
class Exp[T](Derived[T]):
    """
    An exponential of what two metavariables stand for, the base ``B`` to
    the exponent ``E``: ``B << E`` or ``E >> B``.
    """
    exponent: Var[T]
    left: bool = True

    def __str__(self):
        return f"({self.var} << {self.exponent})" if self.left\
            else f"({self.exponent} >> {self.var})"

    @property
    def vars(self) -> tuple[Var, ...]:
        return (self.var, self.exponent)

    @property
    def fixed(self) -> bool:
        return True

    @property
    def length(self) -> int:
        return 1

    def lengths(self, typ, position: int) -> tuple[int, ...]:
        return (1, ) if size(typ) > position else ()

    def value(self, env: dict) -> T:
        base, exponent = self.var.value(env), self.exponent.value(env)
        return base << exponent if self.left else exponent >> base

    def invert(self, value, env: dict) -> dict | None:
        if size(value) != 1 or not getattr(value, "is_exp", False):
            return None
        bound = bind(env, self.var, value.base)
        bound = None if bound is None\
            else bind(bound, self.exponent, value.exponent)
        return bound if bound is not None and self.value(bound) == value\
            else None


@dataclass(frozen=True)
class Word[T](PatternBase[T]):
    """
    A pattern for one boundary of a sequent, the concatenation of
    :data:`Item`\\ s standing for a type: the items are matched in turn,
    a type variable taking every length that leaves a match for the rest,
    and instantiated as the tensor of their values.

    >>> X, A = Var.atom('X'), Var.type('A')
    >>> A @ X.r
    Word(items=(Var.type('A'), Adjoint(var=Var.atom('X'), left=False)))
    """
    items: tuple[Item[T], ...] = ()

    @classmethod
    def of(cls, item) -> Word[T]:
        """ Coerce a word, an item or a tuple of items into a word. """
        if isinstance(item, Word):
            return item
        return cls(tuple(item) if isinstance(item, tuple) else (item, ))

    def __str__(self):
        return " @ ".join(map(str, self.items)) if self.items else "()"

    def __iter__(self):
        return iter(self.items)

    def __len__(self):
        return len(self.items)

    def __matmul__(self, other) -> Word[T]:
        return Word(self.items + Word.of(other).items)

    @property
    def vars(self) -> tuple[Var, ...]:
        found = {}
        for item in self.items:
            for var in item.vars:
                found.setdefault(var.name, var)
        return tuple(found.values())

    @property
    def fixed(self) -> bool:
        """ Whether every item has a length known before matching. """
        return all(item.fixed for item in self.items)

    @property
    def length(self) -> int:
        """ The length of the types a :attr:`fixed` word stands for. """
        return sum(item.length for item in self.items)

    def match(self, value, env: dict = None) -> Iterator[dict]:
        yield from self.matches(value, 0, dict(env or {}))

    def matches(self, typ, position: int, env: dict) -> Iterator[dict]:
        """ The environments matching the items from ``position`` on. """
        if not self.items:
            if position == size(typ):
                yield env
            return
        item, rest = self.items[0], Word(self.items[1:])
        for length, bound in item.bindings(typ, position, env):
            yield from rest.matches(typ, position + length, bound)

    def instantiate(self, env: dict, unit=None) -> T:
        values = [item.value(env) for item in self.items]
        if unit is None:
            first = values[0] if values else next(iter(env.values()))
            if not hasattr(first, "tensor"):
                return values[0]
            unit = first[:0]
        return unit.tensor(*values)


@dataclass(frozen=True)
class Alternatives[T](PatternBase[T]):
    """
    Words for one boundary any of which may match, joined by ``|``:
    ``() | X @ X | X @ X @ X`` for the codomain of a copy.
    """
    options: tuple[Word[T], ...] = ()

    @classmethod
    def of(cls, item) -> Alternatives[T]:
        """ Coerce a word or an item into alternatives of one. """
        if isinstance(item, Alternatives):
            return item
        return cls((Word.of(item), ))

    def __str__(self):
        return " | ".join(map(str, self.options))

    def __or__(self, other) -> Alternatives[T]:
        return Alternatives(self.options + Alternatives.of(other).options)

    @property
    def vars(self) -> tuple[Var, ...]:
        return tuple({
            var.name: var for option in self.options
            for var in option.vars}.values())

    def match(self, value, env: dict = None) -> Iterator[dict]:
        for option in self.options:
            yield from option.match(value, env)

    def instantiate(self, env: dict, unit=None) -> T:
        """ The first option all of whose variables are bound. """
        return next(
            option.instantiate(env, unit) for option in self.options
            if all(var.name in env for var in option.vars))

    def generate(self, draw: Callable, factory, env: dict, **params) -> T:
        from hypothesis import strategies as st

        option = draw(st.sampled_from(self.options))
        return option.generate(draw, factory, env, **params)


@dataclass(frozen=True)
class Sequent[T](PatternBase[T]):
    """
    A pattern for the arrows from what ``dom`` stands for to what ``cod``
    stands for, ``C1[A, B]`` in the annotations of a law or a rule: it
    matches an arrow by its boundaries and generates one through the
    search of the category, :meth:`Testable.strategy` with both.
    """
    dom: Word | Alternatives
    cod: Word | Alternatives

    def __str__(self):
        return f"{self.dom} ⊢ {self.cod}"

    def __iter__(self):
        yield self.dom
        yield self.cod

    @property
    def vars(self) -> tuple[Var, ...]:
        return tuple({
            var.name: var for side in self for var in side.vars}.values())

    @property
    def options(self) -> list[tuple[Word, Word]]:
        """ The pairs of words the sequent stands for, alternatives apart. """
        sides = [
            side.options if isinstance(side, Alternatives) else (side, )
            for side in self]
        return [(dom, cod) for dom in sides[0] for cod in sides[1]]

    def matches(self, dom, cod, env: dict = None) -> Iterator[dict]:
        """ The environments matching the boundaries of a sequent. """
        for bound in self.dom.match(dom, env):
            yield from self.cod.match(cod, bound)

    def match(self, value, env: dict = None) -> Iterator[dict]:
        yield from self.matches(value.dom, value.cod, env)

    def instantiate(self, env: dict, unit=None) -> tuple:
        """ The boundaries the sequent stands for. """
        return self.dom.instantiate(env, unit), self.cod.instantiate(env, unit)

    def generate(self, draw: Callable, factory, env: dict, **params) -> T:
        bound = bind_vars(draw, self.vars, factory, env)
        dom, cod = self.instantiate(bound, unit_of(factory, bound))
        return draw(factory.strategy(dom=dom, cod=cod, **params))

    def canonical(self, factory, env: dict = None, name: str = None) -> T:
        """ A box named ``name`` between the canonical boundaries. """
        dom, cod = super().canonical(factory, env)
        return factory.box_factory(name or "f", dom, cod)


@dataclass(frozen=True)
class Hom[T](PatternBase[T]):
    """
    The terms of a testable class, the arrows of a category, what
    :obj:`C1` stands for in the annotations of a law: ``C1[A, B]`` is the
    :class:`Sequent` of the arrows from ``A`` to ``B``, and :obj:`C1`
    alone any arrow, drawn from the class's own strategy. The class is
    :obj:`None` where it is not known yet, in the annotations of a rule.
    """
    testable: type[T] = None

    def __post_init__(self):
        if self.testable is not None and not (
                isinstance(self.testable, type)
                and issubclass(self.testable, Testable)):
            raise TypeError(
                f"Expected a Testable class, got {self.testable!r}.")

    def __getitem__(self, boundaries) -> Sequent[T]:
        dom, cod = boundaries
        return Sequent(boundary(dom), boundary(cod))

    @property
    def vars(self) -> tuple[Var, ...]:
        return ()

    def match(self, value, env: dict = None) -> Iterator[dict]:
        if isinstance(value, self.testable):
            yield dict(env or {})

    def instantiate(self, env: dict, unit=None) -> T:
        raise TypeError(
            f"A term of {self.testable} is drawn, not instantiated.")

    def generate(self, draw: Callable, factory, env: dict, **params) -> T:
        return draw(self.testable.strategy(**params))

    def canonical(self, factory, env: dict = None, name: str = None) -> T:
        """
        A box named ``name`` from ``x`` to ``y`` when the class has a
        ``box_factory``, else a term of the class named ``name``.
        """
        name = name or "f"
        if hasattr(self.testable, "box_factory"):
            ob = self.testable.ob
            return self.testable.box_factory(name, ob("x"), ob("y"))
        return self.testable(name)


@dataclass(frozen=True)
class Signature[T](PatternBase[T]):
    """
    The pattern of the arguments of a law, one pattern per parameter by
    name, standing for tuples of arguments: the metavariables are shared
    across the patterns and drawn once, so that ``f: C1[A, B], g: C1[B,
    C]`` are composable and ``f: C1[X @ A, X @ B]`` shares its first atom
    with ``x: X``.
    """
    patterns: dict[str, PatternBase] = field(default_factory=dict, hash=False)

    def __str__(self):
        return ", ".join(
            f"{name}: {pattern}" for name, pattern in self.patterns.items())

    @property
    def vars(self) -> tuple[Var, ...]:
        return tuple({
            var.name: var for pattern in self.patterns.values()
            for var in pattern.vars}.values())

    def match(self, value, env: dict = None) -> Iterator[dict]:
        """ The environments matching a tuple of arguments, in order. """
        def go(pairs, env):
            if not pairs:
                yield env
                return
            (pattern, argument), rest = pairs[0], pairs[1:]
            for bound in pattern.match(argument, env):
                yield from go(rest, bound)

        pairs = list(zip(self.patterns.values(), value))
        yield from go(pairs, dict(env or {}))

    def instantiate(self, env: dict, unit=None) -> T:
        return tuple(
            pattern.instantiate(env, unit)
            for pattern in self.patterns.values())

    def generate(self, draw: Callable, factory, env: dict, **params) -> T:
        bound = bind_vars(draw, self.vars, factory, env)
        return tuple(
            pattern.generate(draw, factory, bound, **params)
            for pattern in self.patterns.values())

    def canonical(self, factory, env: dict = None, name: str = None) -> T:
        """ The canonical arguments, each named after its parameter. """
        bound = canonical_vars(self.vars, factory, env)
        return tuple(
            pattern.canonical(factory, bound, name)
            for name, pattern in self.patterns.items())


type Item[T] = Var[T] | Adjoint[T] | Delay[T] | Exp[T]
"""
An item of a :class:`Word`: a metavariable or one derived from it, see
:class:`ItemBase`.
"""

type Pattern[T] = (
    Item[T] | Word[T] | Alternatives[T] | Sequent[T] | Hom[T] | Signature[T])
"""
The sequent-pattern language, closed: every pattern is one of these, each
a :class:`PatternBase`, standing for the objects of a category as an
:data:`Item`, a :class:`Word` or :class:`Alternatives`, for its arrows as
a :class:`Sequent` or a :class:`Hom`, and for the arguments of a law as
a :class:`Signature`.
"""


def boundary(item) -> Word | Alternatives:
    """ Coerce the annotation of a boundary into a word or alternatives. """
    return item if isinstance(item, Alternatives) else Word.of(item)


def bind(env: dict, var: Var, value) -> dict | None:
    """ ``env`` with ``var`` bound to ``value``, or :obj:`None` on a clash. """
    if var.name in env:
        return env if env[var.name] == value else None
    return dict(env, **{var.name: value})


def size(typ) -> int:
    """ The length of a type, one for an object that is not a sequence. """
    return len(typ) if hasattr(typ, "__len__") else 1


def part(typ, start: int, stop: int):
    """ A slice of a type, the object itself when it is not a sequence. """
    if hasattr(typ, "__len__"):
        return typ[start:stop]
    return typ if (start, stop) == (0, 1) else None


def bind_vars(draw: Callable, variables, factory, env: dict) -> dict:
    """ ``env`` extended with a value drawn for each variable not in it. """
    bound = dict(env)
    for var in variables:
        bound[var.name] = var.generate(draw, factory, bound)
    return bound


def canonical_vars(variables, factory, env: dict = None) -> dict:
    """ ``env`` extended with the canonical value of each variable missing. """
    bound = dict(env or {})
    for var in variables:
        bound.setdefault(var.name, var.canonical(factory))
    return bound


def unit_of(factory, env: dict):
    """ The unit type of a factory, read off a bound value if there is one. """
    for value in env.values():
        if hasattr(value, "__len__"):
            return value[:0]
    ob = getattr(factory, "ob", None)
    return ob() if hasattr(ob, "tensor") else None


@cache
def generated() -> Callable:
    """
    The composite strategy of the pattern language, a pattern
    :meth:`PatternBase.generate`\\ ing a value, built once: the decorator
    inspects the function it wraps, a cost not to pay at every draw.
    """
    from hypothesis import strategies as st

    @st.composite
    def generate(draw, pattern, factory, env, params):
        return pattern.generate(draw, factory, env, **params)

    return generate


@dataclass(frozen=True)
class Subspace:
    """
    A subspace a law is :meth:`Axiom.weaken`ed to: a predicate on its
    equation, and the parameters the strategy of the category draws
    inside the subspace with, so that an argument outside it is not drawn
    only to be rejected.

    Parameters:
        predicate : Whether an equation lies in the subspace.
        params : The keyword arguments passed to the category's strategy.
    """

    predicate: Callable
    params: dict = None

    def __call__(self, equation) -> bool:
        return self.predicate(equation)


connected = Subspace(
    lambda equation: all(
        term.is_boundary_connected for term in equation.terms),
    dict(boundary_connected=True))
"""
The subspace where every term of the equation is boundary connected, on
which a normal form is defined: a law compared modulo a normal form is
:meth:`Axiom.weaken`ed to it, and its arguments are drawn with no closed
component tensored on, a trace closing a loop being caught by the
predicate.
"""


def assert_axioms(*categories) -> None:
    """
    Check every axiom of each category on a single generated equation, a
    dry run of the property tests in ``proptest/``.

    An axiom that does not apply is skipped, a broken one is only required
    to raise its :class:`discopy.utils.AxiomError` — one example need not
    be a counterexample — and any other law must hold.
    """
    from hypothesis import Phase, find, settings

    single_shot = settings(
        max_examples=1, phases=(Phase.generate, ), database=None)
    for category in categories:
        for axiom in category.axioms.values():
            if not axiom.parameters and axiom() is NotImplemented:
                continue
            try:
                equation = find(
                    axiom.strategy(), lambda value: True,
                    settings=single_shot)
            except AxiomError:
                assert axiom.broken, axiom
            else:
                assert equation is NotImplemented or equation, axiom


class Serialisable(Testable):
    """
    The serialisation interface of DisCoPy, one hook driving all three
    mechanisms: the class attribute ``serialised_attrs`` names attributes that
    are also keyword arguments of ``__init__``, from which follow

    - a generic pair of inverse methods :meth:`to_tree` and
      :meth:`from_tree`, the JSON serialisation behind
      :func:`discopy.utils.dumps` and :func:`discopy.utils.loads`,
    - a generic :meth:`__repr__` such that ``eval(repr(x)) == x``,
    - :meth:`__setstate__`, the terminal of every pickle migration
      chain; the class parameters of
      :class:`discopy.utils.NamedGeneric` are pickled by their own
      machinery.

    A subclass with a different constructor declares its keys once
    instead of reimplementing each method.

    Each mechanism comes with the law that it is a roundtrip, i.e. that
    a term reads back from what it was written to:
    :meth:`repr_transparency`
    for its representation, :meth:`pickling` and :meth:`copying` for the
    pickle protocol and :meth:`serialisation` for its tree. They are
    axioms like any other, so a class that also implements
    :meth:`discopy.axioms.Testable.strategy` has them checked against
    generated terms, and one that violates a law declares it
    ``.failing`` rather than leaving it untested.

    Example
    -------
    >>> from discopy.cat import Box
    >>> assert Box.serialised_attrs\\
    ...     == ('name', 'dom', 'cod', 'is_dagger', 'data')
    >>> f = Box('f', 'x', 'y', data=42)
    >>> assert Box.from_tree(f.to_tree()) == f
    """
    serialised_attrs: tuple[str, ...] = ()

    def is_default(self, key: str) -> bool:
        """
        Whether the value of an attribute equals its class default,
        in which case :meth:`to_tree` and :meth:`__repr__` drop it.

        Parameters:
            key : The name of the attribute.
        """
        if not hasattr(type(self), key):
            return False
        value, default = getattr(self, key), getattr(type(self), key)
        return value is default or (
            type(value) is type(default) and value == default)

    def __repr__(self):
        """
        The transparent representation of a DisCoPy object: an attribute
        without a class default is positional, one that differs from its
        default is a keyword argument and one equal to it is dropped.

        Example
        -------
        >>> import discopy
        >>> from discopy.cat import Box
        >>> f = Box('f', 'x', 'y', data=42)
        >>> f
        cat.Box('f', cat.Ob('x'), cat.Ob('y'), data=42)
        >>> assert eval(repr(f), vars(discopy)) == f
        """
        return factory_name(type(self)) + "(" + ", ".join(
            f"{key}={repr(getattr(self, key))}" if hasattr(type(self), key)
            else repr(getattr(self, key))
            for key in self.serialised_attrs if not self.is_default(key)) + ")"

    def __setstate__(self, state):
        """
        Restore a pickled state, the terminal that every pickle
        migration shim chains into with ``super().__setstate__``.

        Parameters:
            state : The pickled state of the object.
        """
        self.__dict__.update(state)

    def to_tree(self) -> dict:
        """
        Serialise a DisCoPy object, see :func:`dumps`.

        The tree records the :func:`factory_name` and then each of the
        ``serialised_attrs``, dropping a key when its value equals the
        class attribute of the same name, e.g. a box that is not a
        dagger. An attribute with a ``to_tree`` method is serialised, a
        non-empty list or tuple of such attributes becomes the list of
        their trees, raw JSON data passes through unchanged.

        Example
        -------
        >>> from pprint import PrettyPrinter
        >>> pprint = PrettyPrinter(indent=4, width=70, sort_dicts=False).pprint
        >>> from discopy.cat import Box
        >>> f = Box('f', 'x', 'y', data=42)
        >>> pprint((f >> f[::-1]).to_tree())
        {   'factory': 'cat.Arrow',
            'inside': [   {   'factory': 'cat.Box',
                              'name': 'f',
                              'dom': {'factory': 'cat.Ob', 'name': 'x'},
                              'cod': {'factory': 'cat.Ob', 'name': 'y'},
                              'data': 42},
                          {   'factory': 'cat.Box',
                              'name': 'f',
                              'dom': {'factory': 'cat.Ob', 'name': 'y'},
                              'cod': {'factory': 'cat.Ob', 'name': 'x'},
                              'is_dagger': True,
                              'data': 42}],
            'dom': {'factory': 'cat.Ob', 'name': 'x'},
            'cod': {'factory': 'cat.Ob', 'name': 'x'}}
        """
        tree = {'factory': factory_name(type(self))}
        for key in self.serialised_attrs:
            if self.is_default(key):
                continue
            value = getattr(self, key)
            if hasattr(value, 'to_tree'):
                value = value.to_tree()
            elif isinstance(value, (list, tuple)) and value and all(
                    hasattr(v, 'to_tree') for v in value):
                value = [v.to_tree() for v in value]
            tree[key] = value
        return tree

    @classmethod
    def from_tree(cls, tree: dict) -> Serialisable:
        """
        Decode a serialised DisCoPy object, see :func:`loads`.

        A key missing from the tree falls back to the default value of
        the corresponding keyword argument of ``__init__``. A value with
        a ``'factory'`` key decodes recursively, a non-empty list of
        such values to the tuple of decoded objects, raw JSON data
        passes through unchanged.

        Parameters:
            tree : DisCoPy serialisation.

        Example
        -------
        >>> from discopy.cat import Ob
        >>> assert Ob.from_tree({'factory': 'cat.Ob', 'name': 'x'}) == Ob('x')
        """
        from discopy.utils import from_tree

        kwargs = {}
        for key in cls.serialised_attrs:
            if key not in tree:
                continue
            value = tree[key]
            if isinstance(value, dict) and 'factory' in value:
                value = from_tree(value)
            elif isinstance(value, list) and value and all(
                    isinstance(v, dict) and 'factory' in v for v in value):
                value = tuple(map(from_tree, value))
            kwargs[key] = value
        return cls(**kwargs)

    @classmethod
    def environment(cls) -> dict:
        """
        The namespace the representation of a term reads back in: the
        public names of the package, as ``from discopy import *`` binds
        them, so that a representation qualified by module such as
        ``cat.Box('f', cat.Ob('x'), cat.Ob('y'))`` evaluates, and then
        those of the module the class is defined in, so that one
        printing bare names such as ``Tensor[int]([0], dom=Dim(1),
        cod=Dim(1))`` evaluates too. The module comes second because a
        term prints the names its own module binds: ``Dim`` in
        ``discopy.tensor`` is the one a tensor is built from.

        The import is local because the package imports this module.
        """
        import discopy

        public = lambda namespace: {
            name: value for name, value in namespace.items()
            if not name.startswith("_")}
        module = sys.modules[cls.__module__]
        return dict(public(vars(discopy)), **public(vars(module)))

    @axiom
    def repr_transparency(cls, term: Self) -> Equation:
        """
        The representation of a term evaluates back to it, in the
        :meth:`environment` of its type.

        Its ``str`` reads back too, which STYLE.md asks of every term
        under "the obvious variable naming convention", but the
        environment that convention needs is more than a namespace, so
        ``str_transparency`` is left to
        `#764 <https://github.com/discopy/discopy/issues/764>`_.
        """
        return Equation(eval(repr(term), cls.environment()), term)

    @axiom
    def pickling(cls, term: Self) -> Equation:
        """
        A term loads back from its pickle, of the same class: the equation
        is between the pairs of a class and a term, since a subscript of a
        :class:`discopy.utils.NamedGeneric` is part of what a pickle keeps.
        """
        loaded = pickle.loads(pickle.dumps(term))
        return Equation((type(loaded), loaded), (type(term), term))

    @axiom
    def copying(cls, term: Self) -> Equation:
        """
        A term is equal to its deep copy, of the same class. Copying goes
        through the same protocol as :meth:`pickling` without the bytes,
        so a class whose reduction drops what its state needs — the
        parameters of a :class:`discopy.utils.NamedGeneric`, say — breaks
        one law with the other.
        """
        copied = deepcopy(term)
        return Equation((type(copied), copied), (type(term), term))

    @axiom
    def serialisation(cls, term: Self) -> Equation:
        """
        A term decodes back from its tree and from the JSON of its tree.
        A type without a tree declares the law inapplicable.
        """
        from discopy.utils import dumps, from_tree, loads

        return Equation(from_tree(term.to_tree()), loads(dumps(term)), term)


def assert_strategy_finds(category, *structures: type) -> None:
    """
    Check that the strategy of a diagram category generates a term
    containing a box of each of the given structural classes, the reach a
    module's ``test_strategy`` pins.
    """
    from hypothesis import find

    for structure in structures:
        find(category.strategy(), lambda term: any(
            isinstance(box, structure) for box in term.boxes))
