"""
Property-based testing of the axioms with `Hypothesis
<https://hypothesis.readthedocs.io>`_.

An :class:`Axiom` is an equation stated once on a :class:`Testable`
class — an abstract base class of :mod:`discopy.abc`, whether a category
or the serialisation interface — and inherited by every class below it,
where
:meth:`Axiom.failing` and :meth:`Axiom.inapplicable` classify it when a
class breaks it or has no such structure. A class that implements
:meth:`Testable.strategy` generates its own terms; one that cannot do so
yet leaves the strategy to raise. The matrix in ``proptest/`` reads the
types it quantifies over off :meth:`Testable.subclasses` rather than a
list, and checks every axiom of every type against generated arguments,
one cell per pair; CONTRIBUTING.md says how to run it.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Equation
    Axiom
    AxiomFailure
    Rule
    Testable
    Atomic
    NonEmpty
    BoundaryConnected
    Grid
    ComposablePair
    ComposableTriple
    HorizontalPair
    Square
    TraceSuperposing
    TraceSliding
    TraceNaturalityLeft
    TraceNaturalityRight
    TraceDinaturality
    TraceDinaturalityLeft
    TraceDinaturalityRight
    LeftCurrying
    RightCurrying
    FeedbackVanishing
    FeedbackJoining
    HomogeneousMemory
    Serialisable

.. admonition:: Functions

    .. autosummary::
        :template: function.rst
        :nosignatures:
        :toctree:

        axiom
        rule
        leaf
        search
        resolve
        substitute
        assert_axioms
        assert_strategy_finds

Search strategies as proof search
---------------------------------

A category presented by generators and structural rules is a deductive
system: an object is a sequent ``dom ⊢ cod``, an arrow is a proof, a layer
is a rule application. Generating an arrow with both boundaries fixed —
what every law of a square, a trace or a feedback loop needs — is type
inhabitation in that system, and :func:`search` does it literally, as
backward proof search: from a sequent and a ``size``, the number of boxes
left to place, draw one of the :class:`Rule` that apply, recurse on its
premises, conclude. Every choice is a Hypothesis draw, so Hypothesis's
own search — random generation, shrinking, the example database — is the
control strategy of the proof search, and the category's rules are its
proof system.

The rules are stated once on the abstract base classes of
:mod:`discopy.abc`, beside the axioms that exercise the structure they
generate, and collected through the same walk, :meth:`Testable.declarations`,
so a category generates exactly the structures whose laws it must satisfy.
``Category`` states ``identity`` (``x ⊢ x`` with no box), ``box`` (any
sequent with one box, a fresh generator) and ``cut`` (a drawn middle
boundary, two premises); ``MonoidalCategory`` adds ``tensoring``, a split
of both boundaries whose box-less side is a whiskering; each level then
adds the leaf for its own structure — ``braiding`` on ``x @ y ⊢ y @ x``,
``cupping`` on ``x @ x.r ⊢ ()``, ``copying`` on ``x ⊢ x @ x`` — or a rule
with a premise, ``tracing`` and ``feeding_back``, whose premise is the
sequent extended by a drawn atom of memory. A level drops an inherited
rule by assignment, as for axioms: ``CompactCategory.twisting`` is
:meth:`Rule.inapplicable`. Only the generator class of a level generates
fresh boxes on its own: a structural box such as a cup is generated by the
rules of its category, inside a diagram.

Three facts about this search:

- **It never dead-ends and never filters.** With ``size >= 1`` the
  ``box`` rule always applies; a side that ``tensoring`` gives no box is a
  common prefix or suffix of the boundaries, hence an identity; a
  structural leaf is offered only when its pattern matches. In the
  language of focusing :cite:`Andreoli92`, the invertible rules —
  identity, whiskering, cut through a fresh middle — apply freely and the
  non-invertible ones are pattern-matched. Inhabitation is trivial here
  because the signature is open: a fresh box closes any hole. Deciding
  *equality* of the generated terms is the hard part — unknot-hard for
  braided categories :cite:`DelpeuchVicary21` — and that is the business
  of each level's ``equation_factory``, not of the generator. Fixing the
  signature first would make inhabitation the parsing problem, NP-complete
  for multiplicative linear logic :cite:`LincolnEtAl92` and the Lambek
  calculus :cite:`Pentus06`; a generator never needs to solve it, since it
  draws the derivation and reads the lexicon off its leaves
  :cite:`PalkaEtAl11,LampropoulosEtAl18`.
- **It is complete for the distribution that matters.** Any diagram of
  two layers or more is a cut at a layer boundary and a layer is a tensor
  of boxes and identities, so every diagram between ``dom`` and ``cod`` has
  a derivation, and the size bound is the only knob. A structural leaf
  needs a boundary of a particular shape, which a random type rarely
  takes; the leaf declares that shape with :meth:`Rule.hint`, given the
  sequent, and ``cut`` draws its middle from the hints as well as from the
  types.
- **It shows in the statistics.** Every rule application is a Hypothesis
  ``event``, so ``--hypothesis-show-statistics`` lists how often each rule
  fired in a cell, the input of a strategy audit; and a shrunk
  counterexample is a minimal derivation, since deleting a cut collapses
  the term to a leaf.

The search does not focus the syntax: focused proofs are canonical forms,
and a generator of normal forms would make the interchange, naturality and
sliding laws vacuous. Uniform sampling of large typed terms is a different
problem, solved by Boltzmann samplers :cite:`BendkowskiEtAl18`; the matrix
wants small, shrinkable, structurally diverse terms, which size-indexed
random backward search gives.

Adding a structure to a level means declaring its :class:`Rule` beside its
abstract method — a :func:`leaf` for a box the boundary determines, a
:func:`rule` for one with premises, with a :meth:`Rule.hint` when its
boundary is a shape a random type rarely takes — and pinning the reach in
the module's ``test_strategy`` with :func:`assert_strategy_finds`, inside a
hole with both boundaries fixed where a law needs it there.
"""

from __future__ import annotations

import __future__
import inspect
import pickle
import sys
from collections.abc import Callable
from copy import deepcopy
from dataclasses import KW_ONLY, dataclass, replace
from functools import wraps
from typing import TYPE_CHECKING, ClassVar, Concatenate, Self, TypeVar

from discopy.utils import (
    AxiomError,
    NamedGeneric,
    assert_iscomposable,
    classproperty,
    factory_name,
    get_origin,
)

if TYPE_CHECKING:
    from hypothesis import strategies as st


C0 = TypeVar("C0")
C1 = TypeVar("C1")
"""
The object and arrow types of the category an axiom is bound to.

An axiom annotates its arguments with these rather than with the concrete
types of the module it is written in, so that a subclass inherits the
override with its own types: :meth:`Axiom.strategy` rebinds both names to
``category.ob`` and ``category.ar``, and :data:`typing.Self` to the category
itself for a law of every term of a type whatever its level, such as
:meth:`Serialisable.repr_transparency`, in its :attr:`Axiom.scope` when it
evaluates the annotations; a law of functors names the category they map
from as ``Self.dom``. This is also why every module stating an axiom
needs ``from __future__ import annotations``, which keeps them
unevaluated: :class:`Axiom` refuses an equation compiled without it.
Rebinding happens through the ``locals`` of that evaluation because the
:pep:`695` type parameters of :class:`discopy.abc.Category` live in a
scope :func:`eval` cannot see, in globals or anywhere else.
"""


GENERATORS = tuple("abcde")
"""
The names the generators of a free category are drawn from.

They are finitely many and shared, so a generated functor can name every one
of them: composing two functors keeps only the keys of the left-hand map, so
a functor that named just a few would compose to one defined nowhere else.
"""


class Equation(NamedGeneric["ar"]):
    """
    An equation is a list of ``terms`` to be compared up to a function
    ``up_to``, the identity by default.  Casting it to ``bool`` checks
    whether its terms are all equal up to that function.

    Parameters:
        terms : The terms of the equation.
        symbol : The symbol between each pair of terms, ``"="`` by default.
        symbols : The symbols between each pair of terms, overriding
            ``symbol``; ``len(terms) * (symbol, )`` by default.
        up_to : The function up to which ``bool(equation)`` compares its
            terms, overriding the subclass' :attr:`up_to` if given.

    Example
    -------
    The number of boxes inside an arrow is left unchanged by associativity,
    so we can compare arrows up to the function that counts them modulo 2:

    >>> from discopy.cat import Ob, Box, Equation
    >>> x = Ob('x')
    >>> f, g = Box('f', x, x), Box('g', x, x)
    >>> parity = lambda term: len(term.inside) % 2
    >>> assert not Equation(f, f >> g >> g)
    >>> assert Equation(f, f >> g >> g, up_to=parity)
    """
    up_to = None

    def __init__(self, *terms, symbol="=", symbols=None, up_to=None):
        self.terms = terms
        self.symbols = tuple(symbols) if symbols is not None\
            else len(terms) * (symbol, )
        if up_to is not None:
            self.up_to = up_to

    def modulo(self, up_to: Callable) -> Equation:
        """
        The same equation compared up to the given function, rebinding
        :attr:`up_to`, whose name the attribute already takes.

        >>> from discopy.cat import Ob, Box, Equation
        >>> x = Ob('x')
        >>> f, g = Box('f', x, x), Box('g', x, x)
        >>> assert Equation(f >> g, g >> f).modulo(lambda _: True)
        """
        return type(self)(*self.terms, symbols=self.symbols, up_to=up_to)

    def __repr__(self):
        """
        >>> from discopy.cat import Ob, Box, Equation
        >>> Equation(Box('f', Ob('x'), Ob('x')))
        cat.Equation(cat.Box('f', cat.Ob('x'), cat.Ob('x')))
        """
        return factory_name(type(self))\
            + f"({', '.join(map(repr, self.terms))})"

    def __str__(self):
        return f"Equation({', '.join(map(str, self.terms))})"

    def __bool__(self):
        terms = self.terms if self.up_to is None\
            else list(map(self.up_to, self.terms))
        return all(term == terms[0] for term in terms)


class AxiomFailure(AxiomError):
    """
    A law declared broken, raised when the bound axiom is called: the
    reason is the message and :attr:`equation` is the law evaluated on the
    arguments, whose sides say how it failed.
    """

    def __init__(self, reason: str, equation):
        super().__init__(reason, equation)
        self.equation = equation


@dataclass
class Axiom[**P, T]:
    """
    An axiom of a category, stated once on an abstract base class and
    inherited by every category below it.

    The category is the class the axiom is bound to, e.g.
    :class:`discopy.cat.Arrow` for the axioms of
    :class:`discopy.abc.Category`. The axiom is a classmethod of it,
    implicitly: its first parameter is the category and the remaining ones
    are generated from their annotations — an object for the typing of
    identities, three composable arrows for the associativity of
    composition, a term of the category itself for
    :meth:`Serialisable.repr_transparency`.

    Calling a bound axiom returns its own verdict: :obj:`NotImplemented`
    when the structure does not apply to the category, and the equation
    itself otherwise; a law declared broken raises an
    :class:`AxiomFailure` carrying that equation instead of returning it.

    A law is broken when *some* argument is a counterexample, not every one,
    so :attr:`broken` is declared by :meth:`failing` before any argument is
    generated — the property matrix marks such an axiom as an expected
    failure and lets the search find the counterexample.

    Parameters:
        equation : The function stating the law, from the category and the
            arguments annotated with :obj:`C0`, :obj:`C1`,
            :data:`typing.Self` or a :class:`Testable` to an
            :class:`Equation`, or to :obj:`NotImplemented` when the
            structure does not apply.
        category : The class the axiom is bound to, :obj:`None` until
            :meth:`bind` or the attribute access on a class binds it.
        name : The attribute the law is stored under, the name of the
            equation by default.
        subspaces : The strategies the named parameters are generated from
            instead of their annotations, declared by :meth:`weaken`.
        broken : Whether the law is declared broken by :meth:`failing`.
    """

    equation: Callable[Concatenate[type[T], P], Equation]
    _: KW_ONLY
    category: type[T] = None
    name: str = None
    subspaces: dict = None
    broken: bool = False

    def __post_init__(self):
        function = inspect.unwrap(self.equation)
        deferred = __future__.annotations.compiler_flag
        if not function.__code__.co_flags & deferred:
            raise TypeError(
                f"{function.__module__} states the axiom {function.__name__} "
                "without `from __future__ import annotations`.")
        self.name = self.name or self.equation.__name__
        self.subspaces = dict(self.subspaces or {})
        self.__doc__ = self.equation.__doc__

    def __repr__(self):
        """
        A bound axiom is the attribute of its category, e.g.
        ``cat.Arrow.unitality``; an unbound one wraps a function and has no
        transparent representation.
        """
        if self.category is None:
            return f"{type(self).__name__}({self.name})"
        return f"{factory_name(self.category)}.{self.name}"

    def __hash__(self):
        return hash((self.equation, self.category, self.name))

    def bind(self, category: type[T]) -> Axiom[P, T]:
        """ Bind the axiom to a concrete category. """
        return replace(self, category=category)

    def __get__(self, instance, owner: type[T]) -> Axiom[P, T]:
        return self.bind(owner)

    def modulo(self, up_to) -> Axiom[P, T]:
        """
        The same law with its equation compared up to a function, so that a
        category weakens an inherited axiom in one statement, e.g. a diagram
        compares the interchange law up to its normal form:
        ``Diagram.bifunctoriality = MonoidalCategory.bifunctoriality.modulo(
        Diagram.normal_form)``.
        """
        @wraps(self.equation)
        def equation(*args, **kwargs):
            return self.equation(*args, **kwargs).modulo(up_to)
        return replace(self, equation=equation)

    def failing(self, reason: str) -> Axiom[P, T]:
        """
        The same law declared broken: calling it raises an
        :class:`AxiomFailure` with the reason as message and the equation
        evaluated on the arguments, e.g. ``braid_naturality =
        BraidedCategory.braid_naturality.failing("A free braid is a box.")``.
        """
        @wraps(self.equation)
        def equation(*args, **kwargs):
            raise AxiomFailure(reason, self.equation(*args, **kwargs))
        equation.__doc__ = reason
        return replace(self, equation=equation, broken=True)

    def inapplicable(self, reason: str) -> Axiom[P, T]:
        """
        The same law declared not to apply to the category: it takes no
        argument and returns :obj:`NotImplemented`, with the reason as its
        documentation, e.g. ``trace_vanishing =
        TracedCategory.trace_vanishing.inapplicable("No trace.")``.
        """
        def law(cls):
            return NotImplemented
        law.__doc__ = reason
        return replace(self, equation=law, subspaces={}, broken=False)

    def weaken(self, **subspaces) -> Axiom[P, T]:
        """
        The same law quantified over a subspace of the named arguments,
        e.g. ``unitality_of_loops = Category.unitality.weaken(f=Endo[C1])``
        for a wrapper ``Endo`` of the endomorphisms: each named parameter
        is generated from its subspace strategy, whose wrapper validates
        membership on construction and is unwrapped before the body reads
        it. Assigned to
        its own attribute beside a ``.failing`` declaration, it shows the
        matrix one expected failure and one green cell instead of one
        blanket expected failure.
        """
        return replace(self, subspaces=dict(self.subspaces, **subspaces))

    @property
    def parameters(self) -> tuple[inspect.Parameter, ...]:
        """
        The parameters whose arguments the property matrix generates: all
        but the first, which is the category.
        """
        return tuple(
            inspect.signature(self.equation).parameters.values())[1:]

    @property
    def scope(self) -> dict:
        """
        What the names in the annotations of the axiom stand for: the
        category itself for :data:`typing.Self`, and its objects and arrows
        for :obj:`C0` and :obj:`C1`. A monoid, having no objects of its
        own, stands for both; a class of functors is the arrows of ``Cat``,
        and the category it maps from, where the arguments a functor is
        applied to live, is reachable as ``Self.dom``.
        """
        return {
            "Self": self.category,
            "C0": getattr(self.category, "ob", self.category),
            "C1": getattr(self.category, "ar", self.category)}

    def strategy(self) -> st.SearchStrategy:
        """
        Generate the arguments the bound axiom expects: one per required
        parameter, from its annotation evaluated in the :attr:`scope` of the
        category or from the subspace :meth:`weaken` declared for it.

        Only the parameters' annotations are evaluated: the law's return
        annotation may name a type its module imports for checking only.
        """
        from hypothesis import strategies as st

        if self.category is None:
            raise TypeError(f"{self.name} is not bound to a class.")
        namespace = inspect.unwrap(self.equation).__globals__
        annotations = {
            parameter.name: eval(parameter.annotation, namespace, self.scope)
            if isinstance(parameter.annotation, str) else parameter.annotation
            for parameter in self.parameters}
        annotations.update({
            name: substitute(annotation, self.scope)
            for name, annotation in self.subspaces.items()})
        return st.tuples(*(
            resolve(annotations[parameter.name])
            for parameter in self.parameters
            if parameter.default is inspect.Parameter.empty))

    def falsify(self, **params) -> tuple:
        """
        Search for a shrunk counterexample to the bound axiom: arguments for
        which the verdict fails — the equation is false, or the
        implementation refuses to build its terms — raising
        :class:`hypothesis.errors.NoSuchExample` when no counterexample is
        found. Keyword arguments are passed to :func:`hypothesis.find`.

        >>> from discopy.cat import Arrow
        >>> Arrow.associativity.falsify()  # doctest: +ELLIPSIS
        Traceback (most recent call last):
         ...
        hypothesis.errors.NoSuchExample: No examples found of condition ...
        """
        from hypothesis import find

        def refutes(args):
            try:
                verdict = self(*args)
            except AxiomFailure:
                return True
            return verdict is not NotImplemented and not verdict

        return find(self.strategy(), refutes, **params)

    def arguments(self, *args: P.args, **kwargs: P.kwargs) -> dict:
        """
        Bind the arguments to the :attr:`parameters` of the bound axiom,
        unwrapping those a :attr:`subspaces` wrapper validated on
        construction.
        """
        if self.category is None:
            raise TypeError(f"{self.name} is not bound to a class.")
        bound = inspect.Signature(self.parameters).bind(*args, **kwargs)
        bound.apply_defaults()
        return {
            name: value.value if name in self.subspaces else value
            for name, value in bound.arguments.items()}

    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> Equation[T]:
        return self.equation(self.category, **self.arguments(*args, **kwargs))


def axiom[**P, T](
        equation: Callable[Concatenate[type[T], P], Equation]) -> Axiom[P, T]:
    """
    Decorate an equation as a categorical axiom: a classmethod of its
    category, implicitly, whose remaining parameters are generated.
    """
    return Axiom(equation)


@dataclass
class Rule[T]:
    """
    An inference rule of a category seen as a deductive system: a sequent
    is a pair of objects ``dom ⊢ cod`` with a ``size``, the number of boxes
    left to place, and the rule says whether it :attr:`applies` to the
    sequent and, if chosen, which :attr:`premises` it reduces it to and how
    to conclude the arrow from their proofs. A rule is stated once on an
    abstract base class beside the axioms that exercise the structure it
    generates, and :func:`search` interprets the rules a category inherits.

    Parameters:
        premises : From the category, a Hypothesis ``draw``, the sequent and
            the strategy for ``types``, to the list of premises
            ``(dom, cod, size)`` and the function concluding the arrow from
            their proofs; the draws it makes are those of the rule chosen.
        applies : Whether the rule applies to the sequent, without drawing.
        shape : A strategy for boundaries the rule fires on, given the
            category, the sequent and the strategy for types, declared by
            :meth:`hint` and drawn as a middle boundary by ``Category.cut``.
        category : The class the rule is bound to, :obj:`None` until
            :meth:`bind` or the attribute access on a class binds it.
        name : The attribute the rule is stored under.
    """

    premises: Callable
    applies: Callable
    _: KW_ONLY
    shape: Callable = None
    category: type[T] = None
    name: str = None

    def __post_init__(self):
        self.name = self.name or self.premises.__name__
        self.__doc__ = self.premises.__doc__

    def __repr__(self):
        if self.category is None:
            return f"{type(self).__name__}({self.name})"
        return f"{factory_name(self.category)}.{self.name}"

    def bind(self, category: type[T]) -> Rule[T]:
        """ Bind the rule to a concrete category. """
        return replace(self, category=category)

    def __get__(self, instance, owner: type[T]) -> Rule[T]:
        return self.bind(owner)

    def hint(self, shape: Callable) -> Rule[T]:
        """
        The same rule declaring a strategy for boundaries it fires on, so
        that a cut can draw a middle boundary the rule applies to, e.g.
        ``x @ x.r`` for a cup.
        """
        return replace(self, shape=shape)

    def inapplicable(self, reason: str) -> Rule[T]:
        """
        The same rule declared never to apply to the category, with the
        reason as its documentation, e.g. ``twisting =
        BalancedCategory.twisting.inapplicable("The twist is the identity.")``.
        """
        never = replace(
            self, applies=lambda cls, dom, cod, size: False, shape=None)
        never.__doc__ = reason
        return never


def rule[T](applies: Callable) -> Callable[[Callable], Rule[T]]:
    """
    Decorate the premises of an inference rule with the predicate saying
    when it applies, e.g. ``@rule(lambda cls, dom, cod, size: size >= 2)``
    for a cut.
    """
    return lambda premises: Rule(premises, applies)


def leaf[T](build: Callable) -> Rule[T]:
    """
    Decorate a leaf rule: a function from the category and a sequent to a
    single box concluding it, or :obj:`None` when the boundary has not the
    shape of that box, e.g. a cup on ``x @ x.r ⊢ ()``. It applies to
    sequents of size one whose boundary it builds a box for.
    """
    def premises(cls, draw, dom, cod, size, types):
        return [], lambda: build(cls, dom, cod)

    premises.__name__, premises.__doc__ = build.__name__, build.__doc__
    return Rule(premises, lambda cls, dom, cod, size:
                size == 1 and build(cls, dom, cod) is not None)


def search(
        category, *, types, dom=None, cod=None,
        min_leaves=None, max_leaves) -> st.SearchStrategy:
    """
    Generate arrows of the category by backward proof search over its
    rules: from a sequent ``dom ⊢ cod`` with a ``size`` — the number of
    boxes left to place, drawn within the given bounds — draw a rule among
    those that apply, recurse on its premises and conclude. A boundary
    left :obj:`None` is drawn from ``types``, equal to the other one when no
    box may bridge them. Each application is reported as a Hypothesis
    event, so the statistics of a cell say how often each rule fired.
    """
    from hypothesis import event
    from hypothesis import strategies as st

    @st.composite
    def derive(draw, dom, cod, size):
        applicable = [
            rule for rule in category.rules.values()
            if rule.applies(category, dom, cod, size)]
        chosen = draw(st.sampled_from(applicable))
        event(f"rule: {chosen.name}")
        premises, conclude = chosen.premises(
            category, draw, dom, cod, size, types)
        return conclude(*[draw(derive(*premise)) for premise in premises])

    @st.composite
    def arrows(draw):
        source = draw(types) if dom is None else dom
        target = cod if cod is not None\
            else source if not max_leaves else draw(types)
        source = target if dom is None and not max_leaves else source
        size = draw(st.integers(
            min_value=max(min_leaves or 0, int(source != target)),
            max_value=max_leaves))
        return draw(derive(source, target, size))

    return arrows()


class Testable[T]:
    """
    A testable class states axioms, which its subclasses inherit along
    with the structure they axiomatise, and says how to generate the
    terms those axioms quantify over.

    Both kinds of law meet here: a :class:`discopy.abc.Category` states
    those of a categorical structure, a
    :class:`Serialisable` those of writing a term down and
    reading it back. A class need not be a category to state laws, which
    is why the two meet here rather than in either of them, nor need it
    be either: :class:`ComposablePair` states the law it enforces on the
    pairs it generates.

    A type that implements :meth:`strategy` is one the property matrix
    in ``proptest/`` quantifies over, checking each of its axioms against
    generated terms. One that does not is not checked, and says so by
    leaving :meth:`strategy` to raise.
    """

    @classmethod
    def strategy(cls, **params) -> st.SearchStrategy[T]:
        """
        Build a `search strategy
        <https://hypothesis.readthedocs.io/en/latest/data.html>`_ for
        instances of ``cls``, which is how a class enrols itself in the
        property matrix.

        An override that delegates to another strategy accepts
        ``**params``, pops the parameters it consumes and forwards the
        rest, so that a caller's bounds pass through unchanged and a
        subclass overrides what a base popped just by passing it. A
        terminal strategy instead declares exactly the parameters it
        implements: a constraint it cannot honour fails loudly as an
        unexpected keyword rather than being silently dropped.

        The default raises: a class states its laws as soon as it has
        them, and is checked against them once it says how to draw their
        terms. It is deliberately not an :func:`abc.abstractmethod`,
        which would make every category that has not implemented one
        uninstantiable rather than merely unchecked.

        >>> from discopy.monoidal import Layer
        >>> Layer.strategy()
        Traceback (most recent call last):
         ...
        NotImplementedError: No search strategy implemented for Layer
        """
        raise NotImplementedError(
            f"No search strategy implemented for {cls.__name__}")

    @classmethod
    def declarations(cls, kind: type) -> dict:
        """
        The declarations of a kind inherited by ``cls``, keyed by name and
        bound to ``cls``, an override on a subclass hiding the base it
        overrides.

        Names are collected before they are filtered, so that assigning
        anything that is not of the kind over an inherited declaration drops
        it altogether, rather than restating it.
        """
        visible = {
            name: value
            for base in reversed(cls.__mro__)
            for name, value in base.__dict__.items()}
        return {name: value.bind(cls) for name, value in visible.items()
                if isinstance(value, kind)}

    @classproperty
    def axioms(cls) -> dict[str, Axiom]:
        """ The axioms inherited by ``cls``, see :meth:`declarations`. """
        return cls.declarations(Axiom)

    @classmethod
    def subclasses(cls) -> tuple[type[Testable], ...]:
        """
        Every transitive subclass of ``cls``, ``cls`` itself included.

        A subclass is listed once, however many paths reach it, in the
        order a breadth-first walk of the subclass graph first meets
        it.

        Example
        -------
        >>> from discopy.cat import Arrow, Box
        >>> assert Arrow.subclasses()[0] is Arrow
        >>> assert Box in Arrow.subclasses()  # a subclass of a subclass
        """
        found, queue = {cls: None}, [cls]
        while queue:
            for subclass in queue.pop(0).__subclasses__():
                if subclass not in found:
                    found[subclass] = None
                    queue.append(subclass)
        return tuple(found)


no_strategy = Testable.__dict__["strategy"]
"""
The default :meth:`Testable.strategy`, under a name that can be assigned.

A class inherits it from :class:`Testable` unless a base it refines
implements one: the terms of a :class:`discopy.monoidal.Ty` are not
those of the :class:`discopy.cat.Ob` it subclasses, so a class that
would inherit the wrong strategy declares ``strategy = no_strategy``
until it implements its own.
"""


def factory_of(shape: type) -> type:
    """
    The factory a shape draws its terms from: an unsubscripted shape has
    none, so it has no strategy either, e.g. ``Square`` generates nothing
    where ``Square[Diagram]`` generates squares of diagrams.
    """
    if not isinstance(shape.factory, type):
        raise NotImplementedError(
            f"No search strategy implemented for {shape.__name__}")
    return shape.factory


class Grid(Testable, NamedGeneric["factory"], tuple):
    """ A rectangular grid with composable rows and columns. """

    n_rows: ClassVar[int]
    n_columns: ClassVar[int]
    n_active_rows: ClassVar[int] = 1

    @axiom
    def composability(cls, grid: Self) -> Equation:
        """
        Every cell composes with the cell below it, the law that
        :meth:`__new__` enforces and :meth:`strategy` draws for: the
        codomains of each row are the domains of the row under it.
        """
        above = tuple(
            grid[i].cod for i in range(cls.n_columns * (cls.n_rows - 1)))
        below = tuple(grid[i + cls.n_columns].dom for i in range(len(above)))
        return Equation(above, below)

    def __new__(cls, *cells: C1):
        if len(cells) != cls.n_rows * cls.n_columns:
            raise ValueError("Expected one value per cell.")
        for row in range(cls.n_rows - 1):
            for column in range(cls.n_columns):
                i = row * cls.n_columns + column
                assert_iscomposable(cells[i], cells[i + cls.n_columns])
        for row in range(cls.n_rows):
            for column in range(cls.n_columns - 1):
                i = row * cls.n_columns + column
                cells[i] @ cells[i + 1]
        return super().__new__(cls, cells)

    @classmethod
    def strategy(cls, **params):
        """
        Generate a grid column-by-column using composable boundaries.

        A grid draws its cells from its ``factory``, so an unsubscripted
        one has no strategy: ``ComposablePair`` cannot generate anything,
        ``ComposablePair[Arrow]`` generates pairs of arrows.
        """
        from hypothesis import strategies as st

        factory = factory_of(cls)
        dom, cod = params.pop("dom", None), params.pop("cod", None)

        @st.composite
        def pasting_diagram(draw):
            """ Draw each column as a chain of cells padded by identities. """
            active = draw(st.integers(
                min_value=0,
                max_value=cls.n_rows - cls.n_active_rows))
            columns = []
            for _ in range(cls.n_columns):
                column, boundary = [], dom
                for row in range(cls.n_active_rows):
                    cell = draw(factory.strategy(
                        dom=boundary,
                        cod=cod if row == cls.n_active_rows - 1 else None,
                        **params))
                    column.append(cell)
                    boundary = cell.cod
                columns.append(
                    active * [factory.id(column[0].dom)]
                    + column
                    + (cls.n_rows - active - cls.n_active_rows)
                    * [factory.id(column[-1].cod)])
            return cls(*(
                columns[column][row]
                for row in range(cls.n_rows)
                for column in range(cls.n_columns)))

        return pasting_diagram()


class ComposablePair(Grid):
    """ Two morphisms composable from left to right. """

    n_rows, n_columns = 2, 1
    n_active_rows = 2


class ComposableTriple(Grid):
    """ Three values composable from left to right. """

    n_rows, n_columns = 3, 1
    n_active_rows = 3


class HorizontalPair(Grid):
    """ Two horizontally composable cells. """

    n_rows, n_columns = 1, 2


class Square(Grid):
    """ A two-by-two grid of cells, the arguments of the interchange law. """

    n_rows = n_columns = 2


@dataclass(frozen=True)
class Atomic(Testable, NamedGeneric["factory"]):
    """ An object of the factory containing exactly one generator. """

    value: C0

    def __post_init__(self):
        if len(self.value) != 1:
            raise ValueError("Expected an atomic object.")

    @classmethod
    def strategy(cls, **params):
        """Generate an object of length one."""
        return resolve(factory_of(cls), **{
            **params, "min_length": 1, "max_length": 1}).map(cls)


@dataclass(frozen=True)
class NonEmpty(Testable, NamedGeneric["factory"]):
    """ A non-empty object of the factory. """

    value: C0

    def __post_init__(self):
        if not len(self.value):
            raise ValueError("Expected a non-empty object.")

    @classmethod
    def strategy(cls, **params):
        """Generate an object of length at least one."""
        return resolve(
            factory_of(cls), **{**params, "min_length": 1}).map(cls)


@dataclass(frozen=True)
class BoundaryConnected(Testable, NamedGeneric["factory"]):
    """
    A diagram whose boundary reaches every box, or a grid of such diagrams,
    connected cell by cell: the subspace where a normal form is defined.
    """

    value: C1

    def __post_init__(self):
        cells = self.value if isinstance(self.value, Grid)\
            else (self.value, )
        for cell in cells:
            if not cell.is_boundary_connected:
                raise ValueError("Expected a boundary-connected diagram.")

    @classmethod
    def strategy(cls, **params):
        """Generate from the factory restricted to connected diagrams."""
        return resolve(
            factory_of(cls), boundary_connected=True, **params).map(cls)


class TraceSuperposing(Testable, NamedGeneric["factory"], tuple):
    """ A traceable arrow and an object to superpose. """

    def __new__(cls, traced: C1, obj: C0):
        traced.trace()
        return super().__new__(cls, (traced, obj))

    @classmethod
    def strategy(cls):
        """Generate the identity on an atom and an arbitrary object."""
        from hypothesis import strategies as st

        factory = factory_of(cls)
        return st.tuples(factory.atoms(), factory.ob.strategy()).map(
            lambda pair: cls(factory.id(pair[0]), pair[1]))


class TraceSliding(Testable, NamedGeneric["factory"], tuple):
    """ A traced arrow and one to slide around its trace. """

    left: ClassVar[bool]

    def __new__(cls, traced: C1, obj: C0, sliding: C1):
        traced_dom = obj @ sliding.cod if cls.left else sliding.cod @ obj
        traced_cod = obj @ sliding.dom if cls.left else sliding.dom @ obj
        if (traced.dom, traced.cod) != (traced_dom, traced_cod):
            raise ValueError("Expected compatible trace sliding boundaries.")
        return super().__new__(cls, (traced, obj, sliding))

    @classmethod
    def strategy(cls):
        """Generate the sliding arrow, then the traced one around it."""
        from hypothesis import strategies as st

        factory = factory_of(cls)

        @st.composite
        def arguments(draw):
            obj = draw(factory.ob.strategy(min_length=1))
            dom, cod = draw(factory.ob.strategy()), draw(factory.ob.strategy())
            traced_dom = obj @ cod if cls.left else cod @ obj
            traced_cod = obj @ dom if cls.left else dom @ obj
            traced = draw(factory.strategy(
                dom=traced_dom, cod=traced_cod, min_leaves=1))
            sliding = draw(factory.strategy(dom=dom, cod=cod, min_leaves=1))
            return cls(traced, obj, sliding)

        return arguments()


class TraceNaturalityLeft(TraceSliding):
    """ Arguments for left-oriented trace naturality. """

    left = True


class TraceNaturalityRight(TraceSliding):
    """ Arguments for right-oriented trace naturality. """

    left = False


class TraceDinaturality(Testable, NamedGeneric["factory"], tuple):
    """
    An arrow and one to slide around its trace, traceable only once the
    sliding arrow is composed in on either side.
    """

    left: ClassVar[bool]

    def __new__(cls, traced: C1, sliding: C1):
        traced_in, traced_out = (
            (traced.dom[:len(sliding.cod)], traced.cod[:len(sliding.dom)])
            if cls.left else
            (traced.dom[-len(sliding.cod):], traced.cod[-len(sliding.dom):]))
        if (traced_in, traced_out) != (sliding.cod, sliding.dom):
            raise ValueError("Expected compatible trace sliding boundaries.")
        return super().__new__(cls, (traced, sliding))

    @classmethod
    def strategy(cls):
        """Generate an arrow sliding between the ends of a traced one."""
        from hypothesis import strategies as st

        factory = factory_of(cls)

        @st.composite
        def arguments(draw):
            objects = factory.ob.strategy()
            base, cobase = draw(objects), draw(objects)
            source, target = (
                draw(factory.ob.strategy(min_length=1)) for _ in range(2))
            traced_dom = source @ base if cls.left else base @ source
            traced_cod = target @ cobase if cls.left else cobase @ target
            traced = draw(factory.strategy(
                dom=traced_dom, cod=traced_cod, min_leaves=1))
            sliding = draw(factory.strategy(
                dom=target, cod=source, min_leaves=1))
            return cls(traced, sliding)

        return arguments()


class TraceDinaturalityLeft(TraceDinaturality):
    """ Arguments for left-oriented trace dinaturality. """

    left = True


class TraceDinaturalityRight(TraceDinaturality):
    """ Arguments for right-oriented trace dinaturality. """

    left = False


class LeftCurrying(Testable, NamedGeneric["factory"], tuple):
    """ Arguments for left currying followed by evaluation. """

    left = True

    def __new__(cls, arrow: C1, base: C0, exponent: C0):
        exponential = base << exponent if cls.left else exponent >> base
        arrow_dom = exponential @ exponent if cls.left\
            else exponent @ exponential
        if (arrow.dom, arrow.cod) != (arrow_dom, base):
            raise ValueError("Expected an evaluation morphism.")
        return super().__new__(cls, (arrow, base, exponent))

    @classmethod
    def strategy(cls):
        """Generate an evaluation on two atoms."""
        from hypothesis import strategies as st

        factory = factory_of(cls)
        return st.tuples(factory.atoms(), factory.atoms()).map(
            lambda pair: cls(factory.ev(*pair, left=cls.left), *pair))


class RightCurrying(LeftCurrying):
    """ Arguments for right currying followed by evaluation. """

    left = False


class FeedbackVanishing(Testable, NamedGeneric["factory"], tuple):
    """ A feedback arrow together with the monoidal unit. """

    def __new__(cls, arrow: C1, unit: C0):
        if len(unit):
            raise ValueError("Expected the monoidal unit.")
        arrow.feedback(mem=unit)
        return super().__new__(cls, (arrow, unit))

    @classmethod
    def strategy(cls, **params):
        """Generate an arrow paired with the monoidal unit."""
        factory = factory_of(cls)
        return factory.strategy(**params).map(
            lambda arrow: cls(arrow, factory.ob()))


class FeedbackJoining(Testable, NamedGeneric["factory"], tuple):
    """ A feedback arrow with at least two units of memory. """

    def __new__(cls, arrow: C1, memory: C0):
        if len(memory) < 2:
            raise ValueError("Expected at least two units of memory.")
        if arrow.dom[-len(memory):] != memory.delay():
            raise ValueError("Expected the delayed memory in the domain.")
        if arrow.cod[-len(memory):] != memory:
            raise ValueError("Expected the memory in the codomain.")
        return super().__new__(cls, (arrow, memory))

    @classmethod
    def memories(cls):
        """ A strategy for two units of memory. """
        from hypothesis import strategies as st

        factory = factory_of(cls)
        return st.tuples(factory.atoms(), factory.atoms()).map(
            lambda pair: pair[0] @ pair[1])

    @classmethod
    def strategy(cls):
        """Generate the memory, then an arrow feeding it back."""
        from hypothesis import strategies as st

        factory = factory_of(cls)

        @st.composite
        def arguments(draw):
            obj, memory = draw(factory.ob.strategy()), draw(cls.memories())
            arrow = draw(factory.strategy(
                dom=obj @ memory.delay(), cod=obj @ memory))
            return cls(arrow, memory)

        return arguments()


class HomogeneousMemory(FeedbackJoining):
    """ A feedback arrow whose units of memory are all the same object. """

    def __new__(cls, arrow: C1, memory: C0):
        if any(memory[i:i + 1] != memory[:1] for i in range(len(memory))):
            raise ValueError("Expected homogeneous memory.")
        return super().__new__(cls, arrow, memory)

    @classmethod
    def memories(cls):
        """ A strategy for one unit of memory, twice. """
        return factory_of(cls).atoms().map(lambda atom: atom @ atom)


def resolve(annotation, **params) -> st.SearchStrategy:
    """ Resolve the strategy implemented by an annotated type. """
    if not isinstance(annotation, type)\
            or not issubclass(annotation, Testable):
        raise TypeError(
            f"Expected a Testable annotation, got {annotation!r}.")
    return annotation.strategy(**params)


def substitute(annotation, scope: dict):
    """
    Replace the :obj:`C0` and :obj:`C1` type variables of a subspace
    annotation by the objects and arrows they stand for, rebuilding each
    parameterised wrapper whose factory the substitution changes.
    """
    if isinstance(annotation, TypeVar):
        return scope[annotation.__name__]
    factory = getattr(annotation, "factory", None)
    if factory is None or factory is annotation:
        return annotation
    substituted = substitute(factory, scope)
    if substituted is factory:
        return annotation
    return get_origin(annotation)[substituted]


def assert_axioms(*categories) -> None:
    """
    Check every axiom of each category on a single generated example, a dry
    run of the property tests in ``proptest/``.

    An axiom that does not apply is skipped, a broken one is only required
    to raise its :class:`discopy.utils.AxiomError` — one example need not
    be a counterexample — and any other law must hold.
    """
    from hypothesis import Phase, find, settings

    single_shot = settings(
        max_examples=1, phases=(Phase.generate, ), database=None)
    for category in categories:
        for axiom in category.axioms.values():
            if not axiom.parameters and axiom() is NotImplemented:
                continue
            args = find(
                axiom.strategy(), lambda value: True, settings=single_shot)
            try:
                verdict = axiom(*args)
            except AxiomError:
                assert axiom.broken, axiom
            else:
                assert verdict is NotImplemented or verdict, axiom


class Serialisable(Testable):
    """
    The serialisation interface of DisCoPy, one hook driving all three
    mechanisms: the class attribute ``serialised_attrs`` names attributes that
    are also keyword arguments of ``__init__``, from which follow

    - a generic pair of inverse methods :meth:`to_tree` and
      :meth:`from_tree`, the JSON serialisation behind
      :func:`discopy.utils.dumps` and :func:`discopy.utils.loads`,
    - a generic :meth:`__repr__` such that ``eval(repr(x)) == x``,
    - :meth:`__setstate__`, the terminal of every pickle migration
      chain; the class parameters of
      :class:`discopy.utils.NamedGeneric` are pickled by their own
      machinery.

    A subclass with a different constructor declares its keys once
    instead of reimplementing each method.

    Each mechanism comes with the law that it is a roundtrip, i.e. that
    a term reads back from what it was written to:
    :meth:`repr_transparency`
    for its representation, :meth:`pickling` and :meth:`copying` for the
    pickle protocol and :meth:`serialisation` for its tree. They are
    axioms like any other, so a class that also implements
    :meth:`discopy.axioms.Testable.strategy` has them checked against
    generated terms, and one that violates a law declares it
    ``.failing`` rather than leaving it untested.

    Example
    -------
    >>> from discopy.cat import Box
    >>> assert Box.serialised_attrs\\
    ...     == ('name', 'dom', 'cod', 'is_dagger', 'data')
    >>> f = Box('f', 'x', 'y', data=42)
    >>> assert Box.from_tree(f.to_tree()) == f
    """
    serialised_attrs: tuple[str, ...] = ()

    def is_default(self, key: str) -> bool:
        """
        Whether the value of an attribute equals its class default,
        in which case :meth:`to_tree` and :meth:`__repr__` drop it.

        Parameters:
            key : The name of the attribute.
        """
        if not hasattr(type(self), key):
            return False
        value, default = getattr(self, key), getattr(type(self), key)
        return value is default or (
            type(value) is type(default) and value == default)

    def __repr__(self):
        """
        The transparent representation of a DisCoPy object: an attribute
        without a class default is positional, one that differs from its
        default is a keyword argument and one equal to it is dropped.

        Example
        -------
        >>> import discopy
        >>> from discopy.cat import Box
        >>> f = Box('f', 'x', 'y', data=42)
        >>> f
        cat.Box('f', cat.Ob('x'), cat.Ob('y'), data=42)
        >>> assert eval(repr(f), vars(discopy)) == f
        """
        return factory_name(type(self)) + "(" + ", ".join(
            f"{key}={repr(getattr(self, key))}" if hasattr(type(self), key)
            else repr(getattr(self, key))
            for key in self.serialised_attrs if not self.is_default(key)) + ")"

    def __setstate__(self, state):
        """
        Restore a pickled state, the terminal that every pickle
        migration shim chains into with ``super().__setstate__``.

        Parameters:
            state : The pickled state of the object.
        """
        self.__dict__.update(state)

    def to_tree(self) -> dict:
        """
        Serialise a DisCoPy object, see :func:`dumps`.

        The tree records the :func:`factory_name` and then each of the
        ``serialised_attrs``, dropping a key when its value equals the
        class attribute of the same name, e.g. a box that is not a
        dagger. An attribute with a ``to_tree`` method is serialised, a
        non-empty list or tuple of such attributes becomes the list of
        their trees, raw JSON data passes through unchanged.

        Example
        -------
        >>> from pprint import PrettyPrinter
        >>> pprint = PrettyPrinter(indent=4, width=70, sort_dicts=False).pprint
        >>> from discopy.cat import Box
        >>> f = Box('f', 'x', 'y', data=42)
        >>> pprint((f >> f[::-1]).to_tree())
        {   'factory': 'cat.Arrow',
            'inside': [   {   'factory': 'cat.Box',
                              'name': 'f',
                              'dom': {'factory': 'cat.Ob', 'name': 'x'},
                              'cod': {'factory': 'cat.Ob', 'name': 'y'},
                              'data': 42},
                          {   'factory': 'cat.Box',
                              'name': 'f',
                              'dom': {'factory': 'cat.Ob', 'name': 'y'},
                              'cod': {'factory': 'cat.Ob', 'name': 'x'},
                              'is_dagger': True,
                              'data': 42}],
            'dom': {'factory': 'cat.Ob', 'name': 'x'},
            'cod': {'factory': 'cat.Ob', 'name': 'x'}}
        """
        tree = {'factory': factory_name(type(self))}
        for key in self.serialised_attrs:
            if self.is_default(key):
                continue
            value = getattr(self, key)
            if hasattr(value, 'to_tree'):
                value = value.to_tree()
            elif isinstance(value, (list, tuple)) and value and all(
                    hasattr(v, 'to_tree') for v in value):
                value = [v.to_tree() for v in value]
            tree[key] = value
        return tree

    @classmethod
    def from_tree(cls, tree: dict) -> Serialisable:
        """
        Decode a serialised DisCoPy object, see :func:`loads`.

        A key missing from the tree falls back to the default value of
        the corresponding keyword argument of ``__init__``. A value with
        a ``'factory'`` key decodes recursively, a non-empty list of
        such values to the tuple of decoded objects, raw JSON data
        passes through unchanged.

        Parameters:
            tree : DisCoPy serialisation.

        Example
        -------
        >>> from discopy.cat import Ob
        >>> assert Ob.from_tree({'factory': 'cat.Ob', 'name': 'x'}) == Ob('x')
        """
        from discopy.utils import from_tree

        kwargs = {}
        for key in cls.serialised_attrs:
            if key not in tree:
                continue
            value = tree[key]
            if isinstance(value, dict) and 'factory' in value:
                value = from_tree(value)
            elif isinstance(value, list) and value and all(
                    isinstance(v, dict) and 'factory' in v for v in value):
                value = tuple(map(from_tree, value))
            kwargs[key] = value
        return cls(**kwargs)

    @classmethod
    def environment(cls) -> dict:
        """
        The namespace the representation of a term reads back in: the
        public names of the package, as ``from discopy import *`` binds
        them, so that a representation qualified by module such as
        ``cat.Box('f', cat.Ob('x'), cat.Ob('y'))`` evaluates, and then
        those of the module the class is defined in, so that one
        printing bare names such as ``Tensor[int]([0], dom=Dim(1),
        cod=Dim(1))`` evaluates too. The module comes second because a
        term prints the names its own module binds: ``Dim`` in
        ``discopy.tensor`` is the one a tensor is built from.

        The import is local because the package imports this module.
        """
        import discopy

        public = lambda namespace: {
            name: value for name, value in namespace.items()
            if not name.startswith("_")}
        module = sys.modules[cls.__module__]
        return dict(public(vars(discopy)), **public(vars(module)))

    @axiom
    def repr_transparency(cls, term: Self) -> Equation:
        """
        The representation of a term evaluates back to it, in the
        :meth:`environment` of its type.

        Its ``str`` reads back too, which STYLE.md asks of every term
        under "the obvious variable naming convention", but the
        environment that convention needs is more than a namespace, so
        ``str_transparency`` is left to
        `#764 <https://github.com/discopy/discopy/issues/764>`_.
        """
        return Equation(eval(repr(term), cls.environment()), term)

    @axiom
    def pickling(cls, term: Self) -> Equation:
        """
        A term loads back from its pickle, of the same class: the equation
        is between the pairs of a class and a term, since a subscript of a
        :class:`discopy.utils.NamedGeneric` is part of what a pickle keeps.
        """
        loaded = pickle.loads(pickle.dumps(term))
        return Equation((type(loaded), loaded), (type(term), term))

    @axiom
    def copying(cls, term: Self) -> Equation:
        """
        A term is equal to its deep copy, of the same class. Copying goes
        through the same protocol as :meth:`pickling` without the bytes,
        so a class whose reduction drops what its state needs — the
        parameters of a :class:`discopy.utils.NamedGeneric`, say — breaks
        one law with the other.
        """
        copied = deepcopy(term)
        return Equation((type(copied), copied), (type(term), term))

    @axiom
    def serialisation(cls, term: Self) -> Equation:
        """
        A term decodes back from its tree and from the JSON of its tree.
        A type without a tree declares the law inapplicable.
        """
        from discopy.utils import dumps, from_tree, loads

        return Equation(from_tree(term.to_tree()), loads(dumps(term)), term)


def assert_strategy_finds(category, *structures: type) -> None:
    """
    Check that the strategy of a diagram category generates a term
    containing a box of each of the given structural classes, the reach a
    module's ``test_strategy`` pins.
    """
    from hypothesis import find

    for structure in structures:
        find(category.strategy(), lambda term: any(
            isinstance(box, structure) for box in term.boxes))
