# -*- coding: utf-8 -*-

"""
The free Markov category, i.e. a semicartesian category with a supply of
commutative comonoid, see :cite:t:`FritzLiang23`.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Layer
    Diagram
    Box
    Swap
    Permutation
    Function
    Copy
    Functor


Axioms
------

>>> x = Ty('x')

>>> copy, delete = Copy(x), Copy(x, n=0)

Cocommutative comonoid
======================

>>> counitality = Equation(copy >> delete @ x, Id(x), copy >> x @ delete)
>>> coassociativity = Equation(copy >> copy @ x, copy >> x @ copy)
>>> cocommutativity = Equation(copy >> Swap(x, x), copy)
>>> assert counitality and coassociativity and cocommutativity
>>> Equation(counitality, coassociativity, cocommutativity, symbol='').draw(
...     doctest="docs/_static/frobenius/comonoid.svg")

.. image:: /_static/frobenius/comonoid.svg
    :align: center

Coherence
=========

>>> assert Equation(Diagram.copy(x @ x, n=0), delete @ delete)
>>> assert Equation(Diagram.copy(x @ x),
...     copy @ copy >> x @ Swap(x, x) @ x)

Functions
=========

The structural morphisms generated by swap, copy and delete are the opposites
of functions between finite sets: a :class:`Function` takes its output ``i``
from its input ``fun[i]``, i.e. ``cod[i] == dom[fun[i]]``.

>>> assert Equation(Function(x, [0, 0]), copy)
>>> assert Equation(Function(x, []), delete)
>>> assert Equation(Function(x @ x, [1, 0]), Swap(x, x))

Layers
======

A Markov :class:`Layer` alternates :class:`Function` boxes and generators,
the same way a :class:`discopy.symmetric.Layer` alternates permutations and
generators: it extends :attr:`discopy.symmetric.Layer.plumbing` with
:class:`Function`, so identity routing is stored as its type rather than a
boxed identity function, exactly as for :class:`discopy.symmetric.Layer`.

>>> f = Box('f', x, x @ x)
>>> layer = Layer(x, f, x)
>>> assert layer.boxes_or_types == (x, f, x)
>>> assert not layer.is_plumbing
>>> assert Layer(Function(x, [0, 0])).is_plumbing

Note
----
Equality of Markov diagrams is computed by translation to hypergraph.
Copy boxes are translated to spiders, thus when they appear in the same
diagram as the merge boxes of :mod:`comarkov` they automatically satisfy
the :mod:`frobenius` axioms.
"""

from __future__ import annotations

from collections.abc import Sequence

from discopy import symmetric, monoidal, hypergraph, messages
from discopy.abc import MarkovCategory
from discopy.cat import factory
from discopy.monoidal import Ty, PRO  # noqa: F401
from discopy.python import finset
from discopy.utils import (
    AxiomError, assert_isatomic, factory_name, from_tree)


class Layer(symmetric.Layer):
    """
    A Markov layer, i.e. a :class:`discopy.symmetric.Layer` whose
    :attr:`plumbing` also accepts :class:`Function`.

    Parameters:
        inside : Generators and plumbing, with at least one generator or one
                 non-identity function or permutation.

    Examples
    --------
    >>> x, y = Ty('x'), Ty('y')
    >>> f = Box('f', x, y)
    >>> layer = Layer(x, f, y)
    >>> assert layer.boxes_or_types == (x, f, y)
    >>> assert layer.boxes == [f]
    >>> assert Layer(Function(x, [0, 0])).boxes == []
    """


@factory
class Diagram(symmetric.Diagram, MarkovCategory):
    """
    A Markov diagram is a symmetric diagram with :class:`Copy` boxes.

    Parameters:
        inside(Layer) : The layers inside the diagram.
        dom (monoidal.Ty) : The domain of the diagram, i.e. its input.
        cod (monoidal.Ty) : The codomain of the diagram, i.e. its output.

    Note
    ----
    We can create arbitrary Markov diagrams with the standard notation for
    Python functions.

    >>> x = Ty('x')
    >>> f = Box('f', x, x)

    >>> copy_then_apply = Diagram.from_callable(x, x @ x)(
    ...     lambda x: (f(x), f(x)))

    >>> @Diagram.from_callable(x, x @ x)
    ... def apply_then_copy(x):
    ...     y = f(x)
    ...     return y, y

    >>> Equation(copy_then_apply, apply_then_copy, symbol="$\\\\neq$").draw(
    ...     doctest="docs/_static/markov/copy_and_apply.svg")

    .. image:: /_static/markov/copy_and_apply.svg
    """
    layer_factory = Layer

    @classmethod
    def spider_factory(cls, n_legs_in, n_legs_out, typ, phase=None):
        if phase is not None or n_legs_in != 1:
            raise ValueError
        return cls.copy_factory(typ, n_legs_out)

    @classmethod
    def copy(cls, x: monoidal.Ty, n=2) -> Diagram:
        """
        Make :code:`n` copies of a given type :code:`x`.

        Parameters:
            x : The type to copy.
            n : The number of copies.
        """
        from discopy import frobenius
        return frobenius.Diagram.spiders.__func__(cls, 1, n, x)

    @classmethod
    def discard(cls, x: monoidal.Ty) -> Diagram:
        """
        The discard of a type :code:`x`.

        Parameters:
            x : The type to discard.
        """
        return cls.copy(x, 0)

    @classmethod
    def from_function(cls, fun: Sequence[int], dom: monoidal.Ty = None
                      ) -> Diagram:
        """
        Encode the opposite of a finite-set function natively when the
        category has a matching :class:`Function` factory, the same way
        :meth:`discopy.symmetric.Diagram.from_permutation` encodes a
        permutation. An identity function always becomes the identity
        diagram.

        Parameters:
            fun : A list of integers in ``range(len(dom))``.
            dom : A type, default is :code:`PRO(max(fun) + 1)`.

        Examples
        --------
        >>> x, y = Ty('x'), Ty('y')
        >>> assert Diagram.from_function([1, 0, 1], x @ y)\\
        ...     == Function(x @ y, [1, 0, 1])
        >>> assert Diagram.from_function([0, 1], x @ y) == Id(x @ y)
        """
        fun = list(fun)
        dom = PRO(max(fun) + 1 if fun else 0) if dom is None else dom
        if fun == list(range(len(dom))):
            return cls.id(dom)
        if cls.function_factory.ar is cls:
            return cls.function_factory(dom, fun)
        return cls.function(fun, dom)


class Box(symmetric.Box, Diagram):
    """
    A Markov box is a symmetric box in a Markov diagram.

    Parameters:
        name (str) : The name of the box.
        dom (monoidal.Ty) : The domain of the box, i.e. its input.
        cod (monoidal.Ty) : The codomain of the box, i.e. its output.
    """


class Swap(symmetric.Swap, Box):
    """
    Symmetric swap in a Markov diagram.

    Parameters:
        left (monoidal.Ty) : The type on the top left and bottom right.
        right (monoidal.Ty) : The type on the top right and bottom left.
    """


class Function(Box):
    """
    The opposite of a function between finite sets, i.e. a :class:`Box`
    that copies, deletes and reorders its input wires.

    A function holds a :class:`discopy.python.finset.Function` ``fun`` as
    attribute, with the convention that output wire ``i`` comes from input
    wire ``fun[i]``, i.e. ``cod[i] == dom[fun[i]]``. Bijective functions
    are permutations, non-injective ones copy their inputs and
    non-surjective ones delete them.

    A :class:`Layer` stores it as plumbing rather than as a generator, the
    same way :class:`discopy.symmetric.Permutation` is stored, and the
    identity function is the identity diagram.

    Parameters:
        dom : The domain, i.e. the wires to copy, delete and reorder.
        fun : The function as a :class:`finset.Function` or a list.

    Examples
    --------
    >>> x, y = Ty('x'), Ty('y')
    >>> fun = Function(x @ y, [0, 1, 1])
    >>> assert fun.cod == x @ y @ y
    >>> assert Equation(fun, x @ Copy(y))
    >>> assert Function(x @ y, [0, 1]) == Id(x @ y)
    """
    def __init__(self, dom: monoidal.Ty, fun: Sequence[int]):
        fun = list(fun)
        self.fun = finset.Function(fun, len(dom), len(fun))
        cod = dom[:0].tensor(*(dom[i] for i in self.fun))
        name = f"Function({list(self.fun)})"
        params = dict(
            drawing_name=name, draw_as_wires=True, draw_as_permutation=True,
            permutation_indices=tuple(self.fun)
        ) if self.fun.is_bijective else {}
        super().__init__(name, dom, cod, **params)

    @classmethod
    def cast(cls, box) -> Function:
        """
        Rewrap a structural box into this class, used by :meth:`tensor`.

        >>> x, y = Ty('x'), Ty('y')
        >>> from discopy.symmetric import Permutation
        >>> assert Function.cast(Permutation(x @ y, [1, 0]))\\
        ...     == Function(x @ y, [1, 0])
        """
        if type(box) is cls:
            return box
        return cls(
            box.dom, box.fun if isinstance(box, Function) else box.perm)

    @property
    def is_identity(self) -> bool:
        """
        Whether the underlying function is the identity.

        >>> assert Function(Ty('x', 'y'), [0, 1]).is_identity
        """
        return self.fun.is_identity

    @property
    def size(self) -> int:
        """ Structural functions are not generator boxes in a layer. """
        return 0

    def setoid(self):
        if self.is_identity:
            return (), self.dom, self.cod
        return type(self), self.dom, tuple(self.fun)

    def to_drawing(self):
        """ Draw bijections as a compact band and identities as wires. """
        from discopy.drawing import Drawing
        return Drawing.id(self.dom) if self.is_identity\
            else Drawing.from_box(self)

    def to_copies(self) -> Diagram:
        """
        The same function built as copies followed by a permutation.

        >>> x, y = Ty('x'), Ty('y')
        >>> fun = Function(x @ y, [1, 0, 0])
        >>> assert Equation(fun.to_copies(), fun)
        """
        return self.ar.function(self.fun, self.dom)

    def to_tree(self) -> dict:
        """
        Serialise a function, see :func:`discopy.utils.dumps`.

        >>> from discopy.utils import dumps, loads
        >>> x, y = Ty('x'), Ty('y')
        >>> assert loads(dumps(Function(x @ y, [0, 0])))\\
        ...     == Function(x @ y, [0, 0])
        """
        return dict(factory=factory_name(type(self)),
                    dom=self.dom.to_tree(), fun=list(self.fun))

    @classmethod
    def from_tree(cls, tree: dict) -> Function:
        return cls(from_tree(tree['dom']), tree['fun'])

    def dagger(self) -> Function:
        if not self.fun.is_bijective:
            raise AxiomError(messages.NOT_A_DAGGER.format(self))
        return type(self)(
            self.cod, finset.Permutation(self.fun.inside).dagger())

    def tensor(self, other=None, *others):
        if other is None:
            return self
        if isinstance(other, (Function, symmetric.Permutation)):
            other = type(self).cast(other)
            result = type(self)(
                self.dom @ other.dom, self.fun.tensor(other.fun))
        elif isinstance(other, monoidal.Ty)\
                or isinstance(other, Diagram) and not other.inside:
            typ = other if isinstance(other, monoidal.Ty) else other.dom
            result = type(self)(self.dom @ typ, self.fun.tensor(
                finset.Function.id(len(typ))))
        else:
            result = super().tensor(other)
        return result.tensor(*others)

    def __rmatmul__(self, other):
        if not isinstance(other, monoidal.Ty):
            return super().__rmatmul__(other)
        fun = finset.Function.id(len(other)).tensor(self.fun)
        return type(self)(other @ self.dom, fun)

    def __repr__(self):
        return f"{factory_name(type(self))}({self.dom!r}, {list(self.fun)})"

    def __str__(self):
        return f"Function({self.dom}, {list(self.fun)})"


class Permutation(symmetric.Permutation, Box):
    """
    A permutation in a Markov category, i.e. a bijective :class:`Function`.

    Parameters:
        dom (monoidal.Ty) : The domain, i.e. the wires to permute.
        perm : The permutation as a :class:`finset.Permutation` or a list.
    """
    fun = property(lambda self: self.perm)

    def tensor(self, other=None, *others):
        if isinstance(other, Function):
            return self.ar.function_factory.cast(self).tensor(other, *others)
        return super().tensor(other, *others)


class Trace(symmetric.Trace, Box):
    """
    A trace in a Markov category.

    Parameters:
        arg : The diagram to trace.
        left : Whether to trace the wires on the left or right.

    See also
    --------
    :meth:`Diagram.trace`
    """


class Copy(Box):
    """
    The copy of an atomic type :code:`x` some :code:`n` number of times.

    Parameters:
        x : The type to copy.
        n : The number of copies.
    """
    def __init__(self, x: monoidal.Ty, n: int = 2):
        assert_isatomic(x, monoidal.Ty)
        name = f"Copy({x}" + ("" if n == 2 else f", {n}") + ")"
        Box.__init__(self, name, dom=x, cod=x ** n,
                     draw_as_spider=True, color="black", drawing_name="")

    def __new__(cls, x: monoidal.Ty, n: int = 2):
        return super().__new__(cls) if n else\
            cls.discard_factory.__new__(cls.discard_factory, x)

    def dagger(self):
        if not hasattr(self.ar, "merge_factory"):
            raise AxiomError(messages.NOT_A_DAGGER.format(self))
        return self.ar.merge_factory(self.dom, len(self.cod))

    def __repr__(self):
        return (
            factory_name(type(self)) + f"({repr(self.dom)}, {len(self.cod)})")


class Discard(Copy):
    """
    The discard of an atomic type :code:`x`.

    Parameters:
        x : The type to discard.
    """
    def __init__(self, x: monoidal.Ty, *args, **kwargs):
        super().__init__(x, 0)


class Sum(symmetric.Sum, Box):
    """
    A markov sum is a symmetric sum and a markov box.

    Parameters:
        terms (tuple[Diagram, ...]) : The terms of the formal sum.
        dom (Ty) : The domain of the formal sum.
        cod (Ty) : The codomain of the formal sum.
    """


class Functor(symmetric.Functor):
    """
    A Markov functor is a symmetric functor that preserves copies.

    Parameters:
        ob_map (Mapping[monoidal.Ty, monoidal.Ty]) :
            Map from :class:`monoidal.Ty` to :code:`cod.ob`.
        ar_map (Mapping[Box, Diagram]) : Map from :class:`Box` to :code:`cod`.
        cod (Category) :
            The codomain, :code:`Diagram` by default.

    Example
    -------

    We build a functor into python functions.

    >>> x = Ty('x')
    >>> add = Box('add', x @ x, x)
    >>> from discopy import python
    >>> F = Functor({x: int}, {add: lambda a, b: a + b},
    ...             cod=python.Function)
    >>> copy = Copy(x)
    >>> bialgebra_l = copy @ copy >> Id(x) @ Swap(x, x) @ Id(x) >> add @ add
    >>> bialgebra_r = add >> copy
    >>> assert F(bialgebra_l)(54, 46) == F(bialgebra_r)(54, 46)
    >>> assert F(Function(x @ x, [1, 0, 0]))(4, 2) == (2, 4, 4)

    >>> Equation(bialgebra_l, bialgebra_r, symbol="=").draw(
    ...     doctest="docs/_static/markov/bialgebra.svg")

    .. image:: /_static/markov/bialgebra.svg
    """
    dom = cod = Diagram

    def __call__(self, other):
        if isinstance(other, Copy) and hasattr(self.cod, "copy"):
            return self.cod.copy(self(other.dom), len(other.cod))
        if isinstance(other, Function)\
                and not isinstance(other, symmetric.Permutation):
            dom = self(other.dom)
            return self.cod.ar.id(dom) if other.is_identity\
                else self.cod.ar.function(other.fun, dom)
        return super().__call__(other)


class CMap(symmetric.CMap):
    category = Diagram


Diagram.functor_factory = Functor
Diagram.map_factory = CMap
Hypergraph = hypergraph.Hypergraph[Diagram]
Diagram.copy_factory = Copy
Diagram.swap_factory = Swap
Diagram.permutation_factory = Permutation
Diagram.function_factory = Function
Diagram.trace_factory = Trace
Diagram.discard_factory = Discard
Diagram.sum_factory = Sum
Layer.plumbing = (monoidal.Ty, Function, symmetric.Permutation)
Id = Diagram.id


class Equation(symmetric.Equation):
    """ The :class:`symmetric.Equation` of Markov diagrams. """
    up_to = staticmethod(Diagram.to_hypergraph)
