# -*- coding: utf-8 -*-
import networkx as nx
from discopy import monoidal
from discopy.utils import factory


class Box(monoidal.Box):
    """
    The monoidal signature based on a directed graph
    An arrow in the free category generated by the signature
    """
    def __init__(self, graph: nx.DiGraph, node: str, ):
        super().__init__(
            node,
            monoidal.Ty(*sorted(graph.predecessors(node))),
            monoidal.Ty(*sorted(graph.successors(node))))
