# -*- coding: utf-8 -*-

"""
The free compact category generated by networks, i.e. the geometry of
interaction of neural networks.

A :class:`Ty` is a list of :class:`Leg`, each a shape with a direction: a
forward leg carries a tensor from the top of a diagram to the bottom and its
adjoint ``x.r`` carries one back up. A :class:`Box` from ``dom`` to ``cod``
is a :class:`Network` from ``dom.positive @ cod.negative``, the legs it
reads, to ``cod.positive @ dom.negative``, the legs it writes: a feedforward
network from ``X`` to ``Y`` is the box from ``Ty(X)`` to ``Ty(Y)`` with
forward legs only, and its transpose is the same network read from below.
Cups and caps bend legs around, they compute the identity, so that a diagram
composes its boxes by symmetric feedback: this is the Int-construction of
Joyal, Street & Verity :cite:p:`JoyalEtAl96` applied to networks, the
geometry of interaction of Abramsky :cite:p:`Abramsky96`, see
:mod:`discopy.interaction`. :meth:`Diagram.to_int` evaluates a diagram there.

:class:`CMap` is the combinatorial map of a diagram and
:meth:`CMap.to_network` its execution formula: the networks of all the boxes
side by side, one permutation routing each leg written to the leg that reads
it, and a trace feeding the boxes back to each other. It is one flat network
computing the same as the composition in ``Int(Network)``, with one trace for
the whole diagram rather than one per composition.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Leg
    Ty
    Diagram
    Box
    Cup
    Cap
    Swap
    Permutation
    Functor
    CMap

Axioms
------

>>> x = Ty(2)
>>> assert Equation(Id(x.r).transpose(left=True), Id(x), Id(x.r).transpose())
>>> assert Equation(Cap(x, x.r) >> Swap(x, x.r), Cap(x.r, x))
>>> assert Equation(Swap(x, x.r) >> Cup(x.r, x), Cup(x, x.r))

Example
-------

The execution formula of a composition is the composition of the networks,
up to the axioms of traced categories, and that of a snake is the identity.

>>> from discopy.neural import network
>>> f = network.Box('f', Dims(2), Dims(3))
>>> g = network.Box('g', Dims(3), Dims(1))
>>> F, G = Box('f', x, Ty(3), network=f), Box('g', Ty(3), Ty(1), network=g)
>>> assert network.Equation((F >> G).to_map().to_network(), f >> g)
>>> assert network.Equation(
...     Id(x).transpose().to_map().to_network(), Network.id(Dims(2)))
>>> (F >> G).to_map().to_network().draw(
...     doctest="docs/_static/neural/execution-formula.svg")

.. image:: /_static/neural/execution-formula.svg
    :align: center
"""

from __future__ import annotations

from discopy import cmap, compact, interaction, messages, pivotal
from discopy.cat import factory
from discopy.monoidal import Dim
from discopy.neural.network import Dims, Network
from discopy.utils import assert_isinstance, factory_name, from_tree


class Leg(pivotal.Wire):
    """
    A leg is a shape with a direction: forward for ``z == 0``, from the top
    of a diagram to the bottom, and backward for its adjoint ``z == 1``.

    Parameters:
        dim : The shape of the leg, an integer standing for a vector.
        z : Whether the leg is backward.

    Example
    -------
    >>> x = Leg(Dim(2, 3))
    >>> assert x.r == x.l == Leg(Dim(2, 3), z=1) and x.r.r == x
    >>> print(x.r)
    Dim(2, 3).r
    """
    def __init__(self, dim: Dim | int, z: int = 0):
        self.dim = Dim(dim) if isinstance(dim, int) else dim
        assert_isinstance(self.dim, Dim)
        super().__init__(str(self.dim), z)

    l = r = property(lambda self: type(self)(self.dim, (self.z + 1) % 2))

    def __repr__(self):
        return f"Leg({self.dim!r}" + (f", z={self.z})" if self.z else ")")

    def to_tree(self) -> dict:
        tree = {'factory': factory_name(type(self)), 'dim': self.dim.to_tree()}
        return tree | ({'z': self.z} if self.z else {})

    @classmethod
    def from_tree(cls, tree: dict) -> Leg:
        return cls(from_tree(tree['dim']), tree.get('z', 0))


@factory
class Ty(pivotal.Ty):
    """
    A type is a list of legs, given by their shapes or as a :class:`Dims`
    for forward legs, with ``.r`` the adjoint turning every leg around.

    Parameters:
        inside : The legs, or the shapes of forward ones.

    Example
    -------
    >>> x = Ty(2, Dim(2, 3))
    >>> assert x == Ty(Dims(2, Dim(2, 3))) == Ty(Leg(2), Leg(Dim(2, 3)))
    >>> assert x.l == x.r == Ty(Leg(Dim(2, 3), z=1), Leg(2, z=1))
    >>> assert x.r.r == x
    >>> print(x @ x.r)
    Dim(2) @ Dim(2, 3) @ Dim(2, 3).r @ Dim(2).r
    >>> (x @ x.r).positive, (x @ x.r).negative
    (Dims(Dim(2), Dim(2, 3)), Dims(Dim(2), Dim(2, 3)))
    """
    generator_factory = Leg

    def __init__(self, *inside: int | Dim | Dims | Leg, **kwargs):
        inside = kwargs.pop('inside', inside)
        legs = tuple(
            leg for x in inside
            for leg in (x.inside if isinstance(x, Dims) else (x, )))
        super().__init__(
            *(Leg(x) if isinstance(x, (int, Dim)) else x for x in legs),
            **kwargs)

    def __repr__(self):
        return f"Ty({', '.join(map(repr, self.inside))})"

    @property
    def positive(self) -> Dims:
        """ The shapes of the forward legs, in order. """
        return Dims(*(leg.dim for leg in self.inside if not leg.z))

    @property
    def negative(self) -> Dims:
        """
        The shapes of the backward legs, in reverse order as the adjoint of
        a tensor comes.
        """
        return Dims(*(leg.dim for leg in reversed(self.inside) if leg.z))

    def to_int(self) -> interaction.Ty:
        """ The pair of halves of the type, an object of ``Int(Network)``. """
        return interaction.Ty[Dims](self.positive, self.negative)


@factory
class Diagram(compact.Diagram):
    """
    A diagram is a compact diagram with lists of legs as objects: the free
    compact category on its boxes, evaluated in ``Int(Network)`` by
    :meth:`to_int`.

    Parameters:
        inside (Layer) : The layers of the diagram.
        dom (Ty) : The legs at the top of the diagram.
        cod (Ty) : The legs at the bottom of the diagram.
    """
    ob = Ty

    def to_map(self) -> CMap:
        """ The combinatorial map of the diagram. """
        return CMap.from_diagram(self)

    def to_int(self) -> interaction.Diagram:
        """
        Evaluate the diagram in ``Int(Network)``, i.e. the execution formula
        of its combinatorial map, see :meth:`CMap.to_network`.
        """
        return self.to_map().to_int()


class Box(compact.Box, Diagram):
    """
    A box from ``dom`` to ``cod`` is a network from
    ``dom.positive @ cod.negative``, the legs it reads, to
    ``cod.positive @ dom.negative``, the legs it writes, or a symbol when
    ``network`` is left to ``None``.

    Parameters:
        name : The name of the box.
        dom : The legs at the top of the box.
        cod : The legs at the bottom of the box.
        network : The network computing the box.

    Note
    ----
    The network is that of the generator: the dagger and the transpose of a
    box keep it, and :meth:`to_network` reads it as the box stands, i.e.
    daggered when the box is and with its legs swapped around when the box
    is rotated.

    Example
    -------
    >>> from discopy.neural import network
    >>> k = network.Box('k', Dims(2, 5), Dims(3, 4))
    >>> K = Box('k', Ty(2, Leg(4, z=1)), Ty(3, Leg(5, z=1)), network=k)
    >>> assert K.r.r == K and K.r.network == k
    >>> assert K.r.to_network() == Network.swap(Dims(5), Dims(2)) >> k\\
    ...     >> Network.swap(Dims(3), Dims(4))
    >>> assert K.dagger().to_network() == k.dagger()
    """
    network = None

    def __init__(self, name: str, dom: Ty, cod: Ty, network: Network = None,
                 data=None, is_dagger: bool = False, z: int = 0, **params):
        network = data if network is None else network
        if network is not None:
            assert_isinstance(network, Network)
            source, target = (cod, dom) if is_dagger else (dom, cod)
            if z % 2:
                source, target = target.r, source.r
            reads = source.positive @ target.negative
            writes = target.positive @ source.negative
            if network.dom != reads:
                raise ValueError(messages.WRONG_DOM.format(reads, network.dom))
            if network.cod != writes:
                raise ValueError(messages.WRONG_COD.format(
                    writes, network.cod))
        self.network = network
        super().__init__(name, dom, cod, data=network,
                         is_dagger=is_dagger, z=z, **params)

    def __repr__(self):
        if self.is_dagger:
            return repr(self.dagger()) + ".dagger()"
        network = "" if self.network is None else f", network={self.network!r}"
        z = f", z={self.z}" if self.z else ""
        return f"{factory_name(type(self))}("\
            f"{self.name!r}, {self.dom!r}, {self.cod!r}{network}{z})"

    def to_network(self) -> Network:
        """
        The network the box computes as it stands, from the legs it reads to
        the legs it writes.
        """
        if self.network is None:
            raise ValueError(f"{self} has no network.")
        network = self.network.dagger() if self.is_dagger else self.network
        if not self.z % 2:
            return network
        return Network.swap(self.dom.positive, self.cod.negative) >> network\
            >> Network.swap(self.dom.negative, self.cod.positive)

    def to_tree(self) -> dict:
        tree = super().to_tree()
        tree.pop('data', None)
        if self.network is not None:
            tree['network'] = self.network.to_tree()
        if self.z:
            tree['z'] = self.z
        return tree

    @classmethod
    def from_tree(cls, tree: dict) -> Box:
        dom, cod = map(from_tree, (tree['dom'], tree['cod']))
        network = from_tree(tree['network']) if 'network' in tree else None
        return cls(tree['name'], dom, cod, network=network,
                   is_dagger='is_dagger' in tree, z=tree.get('z', 0))


class Cup(compact.Cup, Box):
    """
    A cup bends a leg around, reading it from above and writing it below.

    Parameters:
        left (Ty) : The leg.
        right (Ty) : Its adjoint.
    """


class Cap(compact.Cap, Box):
    """
    A cap bends a leg around, reading it from below and writing it above.

    Parameters:
        left (Ty) : The leg.
        right (Ty) : Its adjoint.
    """


class Permutation(compact.Permutation, Box):
    """
    A permutation of legs.

    Parameters:
        dom (Ty) : The legs to permute.
        perm : The permutation as a :class:`finset.Permutation` or a list.
    """


class Swap(Permutation, compact.Swap, Box):
    """
    The swap of two legs.

    Parameters:
        left (Ty) : The leg on the top left and bottom right.
        right (Ty) : The leg on the top right and bottom left.
    """


class Functor(compact.Functor):
    """
    A compact functor between diagrams of networks.

    Parameters:
        ob_map (Mapping[Ty, Ty]) : Map from atomic :class:`Ty` to `cod.ob`.
        ar_map (Mapping[Box, Diagram]) : Map from :class:`Box` to `cod`.
        cod (Category) : The codomain, :code:`Diagram` by default.
    """
    dom = cod = Diagram


class CMap(cmap.CMap[Diagram]):
    """
    A combinatorial map with networks as boxes and legs as ports: each wire
    joins the port writing a leg to the port reading it.

    Example
    -------
    The map of a diagram composes its networks side by side rather than one
    after the other: a leg of one box reaches another through the routing
    permutation and the trace, see :meth:`to_network`.

    >>> from discopy.neural import network
    >>> x, h = Dims(2), Dims(4)
    >>> cell = network.Box('cell', x @ h, x @ h)
    >>> C = Box('cell', Ty(x @ h), Ty(x @ h), network=cell)
    >>> recurrent = (C >> C).trace()
    >>> assert not recurrent.to_map().is_acyclic
    >>> assert network.Equation(
    ...     recurrent.to_map().to_network(), (cell >> cell).trace())
    """
    def to_network(self) -> Network:
        """
        The execution formula of the map: the networks of its boxes side by
        side, one permutation routing each leg written to the leg that reads
        it and a trace feeding the boxes back to each other, a network from
        ``dom.positive @ cod.negative`` to ``cod.positive @ dom.negative``.

        A forward leg is written at the input of the map and at the output
        of a box, and read at the output of the map and at the input of a
        box; a backward leg the other way around. Each wire joins a writer
        to a reader, so the routing is the permutation from the legs
        written, those of the network's input followed by those the boxes
        write, to the legs read, those of the network's output followed by
        those the boxes read.

        Example
        -------
        >>> from discopy.neural import network
        >>> f = network.Box('f', Dims(2), Dims(3))
        >>> F = Box('f', Ty(2), Ty(3), network=f)
        >>> print(F.to_map().to_network())
        Trace(Swap(Dims(Dim(2)), Dims(Dim(3))) >> Dims(Dim(3)) @ f)
        >>> assert F.transpose().to_map().to_network()\\
        ...     == F.to_map().to_network()
        """
        ports = self.ports

        def split(indices: tuple[int, ...]) -> tuple[list[int], list[int]]:
            forward = [i for i in indices if not ports[i].obj.z]
            backward = [i for i in reversed(indices) if ports[i].obj.z]
            return forward, backward

        def legs(indices: list[int]) -> Dims:
            return Dims(*(ports[i].obj.inside[0].dim for i in indices))

        n_dom, n_cod = len(self.dom), len(self.cod)
        dom_forward, dom_backward = split(tuple(range(n_dom)))
        cod_forward, cod_backward = split(
            tuple(range(self.n_ports - n_cod, self.n_ports)))
        writers = dom_forward + cod_backward
        readers = cod_forward + dom_backward
        for index, box in enumerate(self.boxes):
            box_ports = self.box_ports(index)
            box_dom, box_cod = (
                box_ports[:len(box.dom)], box_ports[len(box.dom):])
            (reads, writes_back), (writes, reads_back) = map(
                split, (box_dom, box_cod))
            writers += writes + writes_back
            readers += reads + reads_back
        position = {port: i for i, port in enumerate(writers)}
        routing = Network.from_permutation(
            [position[self.edges[port]] for port in readers], legs(writers))
        boxes = Network.id(Dims()).tensor(
            *(box.to_network() for box in self.boxes))
        boundary = Network.id(legs(cod_forward + dom_backward))
        result = (routing >> boundary @ boxes).trace(len(boxes.cod))
        for loop in self.loops:
            result = result @ Network.id(Dims(loop.inside[0].dim)).trace()
        return result

    def to_int(self) -> interaction.Diagram:
        """ The map in ``Int(Network)``, see :meth:`to_network`. """
        return interaction.Int(Network)(
            self.to_network(), self.dom.to_int(), self.cod.to_int())


Id = Diagram.id
Equation = compact.Equation

Diagram.functor_factory = Functor
Diagram.swap_factory = Swap
Diagram.permutation_factory = Permutation
Diagram.cup_factory, Diagram.cap_factory = Cup, Cap
