# -*- coding: utf-8 -*-

"""
The free compact closed category of bidirectional neural networks, with
additive dimensions as objects and concatenation as tensor.

A :class:`Network` with domain ``Dim(a_1, ..., a_m)``, codomain
``Dim(b_1, ..., b_n)`` and private memory ``Dim(c_1, ..., c_k)`` carries one
backend-owned callable from ``R ** w`` to ``R ** w`` for
``w = sum(a_i) + sum(b_i) + sum(c_i)``. It reads incoming messages on all its
public ports followed by its previous private memory, and emits outgoing
public messages followed by its next private memory.
Networks compose with the cartesian product of vector spaces, so the tensor
of dimensions is their sum with the zero-dimensional space ``Dim(0)`` as
unit; dimensions are self-dual so that cups, caps and swaps are pure
rerouting.

A morphism is a graph neural network: :meth:`CMap.forward` does synchronous
message passing along the wires, which approximates the execution formula of
the geometry of interaction, see :cite:t:`Abramsky96` and
:mod:`discopy.interaction` for the Int-construction of Joyal, Street & Verity
:cite:p:`JoyalEtAl96`.

Only the syntax is compact closed: the free category is generated by networks
and its cups and caps are rerouting, but the networks themselves do not form a
traced category. A trace would ask for the fixed point of the execution
formula, whereas :meth:`CMap.forward` runs a fixed number of rounds and is not
guaranteed to reach one.

Summary
-------

.. autosummary::
    :template: class.rst
    :nosignatures:
    :toctree:

    Dim
    Diagram
    Network
    Cup
    Cap
    Swap
    Functor
    Hypergraph
    Para
    CMap
    Execution

Example
-------

Message passing on the combinatorial map of a diagram computes its image
under the execution formula, e.g. rerouting for a snake:

>>> import torch  # doctest: +EXTRA
>>> snake = Id(Dim(2)).transpose().to_map()
>>> snake.boxes
()
>>> x = torch.tensor([[0.1, 0.2]])
>>> assert (snake(x) == x).all()
"""

from __future__ import annotations

from functools import cached_property

from discopy import compact, hypergraph, monoidal, para
from discopy.cat import factory
from discopy.cmap import PortKind
from discopy.neural.backend import Backend, get_backend
from discopy.pivotal import Ty
from discopy.utils import (
    assert_isinstance, factory_name, from_tree as decode)


@factory
class Dim(monoidal.Dim, Ty):
    """
    A dimension is a tuple of positive integers seen as a self-dual type,
    with addition as tensor and the zero-dimensional space as unit.

    Example
    -------
    >>> assert Dim(0) == Dim() and Dim(0) @ Dim(2) @ Dim(3) == Dim(2, 3)
    >>> assert Dim(2, 3).l == Dim(2, 3).r == Dim(3, 2)
    """
    unit = 0
    l = r = property(lambda self: self.ar(*self.inside[::-1]))

    def unwind(self) -> Dim:
        """ Dimensions have no winding number to normalize. """
        return self

    def to_tree(self) -> dict:
        """ Serialize an additive dimension. """
        return {
            'factory': factory_name(type(self)),
            'inside': list(self.inside)}

    @classmethod
    def from_tree(cls, tree: dict) -> Dim:
        """ Deserialize an additive dimension. """
        return cls(*tree['inside'])


@factory
class Diagram(compact.Diagram):
    """
    A neural diagram is a compact diagram with dimensions as objects.

    Parameters:
        inside (Layer) : The layers of the diagram.
        dom (Dim) : The domain of the diagram, i.e. its input.
        cod (Dim) : The codomain of the diagram, i.e. its output.
    """
    ob = Dim


class Network(compact.Box, Diagram):
    """
    A network is a neural box together with a backend module computing it.

    A network is a cell of a message-passing network rather than a
    feedforward layer: its module maps ``R ** width`` to ``R ** width`` for
    ``width`` the sum of the domain, codomain and private memory dimensions,
    i.e. it reads one incoming message and emits one outgoing message on
    every public port at once, in the order given by the domain followed by
    the codomain, then reads the previous memory and emits the next memory.
    A feedforward layer is the special case of a module which ignores the
    messages incoming on its codomain, executed with
    :meth:`CMap.forward` and ``causal=True`` so that every box fires once in
    topological order. Reusing the same network instance, or the same module,
    as several boxes shares its weights but each box occurrence has its own
    memory.

    Cups, caps and swaps are networks with ``module`` left to ``None``,
    since they are pure rerouting.

    Parameters:
        name : The name of the network.
        dom : The domain of the network, i.e. its input.
        cod : The codomain of the network, i.e. its output.
        module : The backend-owned module of the network.
        mem : The private memory dimension.

    Note
    ----
    Networks compare equal when they have the same name, shape, memory and
    module, where missing modules compare equal and given modules compare
    by identity. The dagger and rotation of a network reuse its module and
    preserve its private memory, with the public ports read in the new order.

    Example
    -------
    >>> import torch  # doctest: +EXTRA
    >>> f = Network('f', Dim(2), Dim(3), module=torch.nn.Linear(5, 5))
    >>> g = Network('g', Dim(3), Dim(2), module=torch.nn.Linear(5, 5))
    >>> (f >> g).dom == (f >> g).cod == Dim(2)
    True
    >>> f.module(torch.ones(1, 5)).shape
    torch.Size([1, 5])
    >>> assert f[::-1].module is f.module
    """
    module, mem = None, Dim()

    def __init__(self, name: str, dom: Dim, cod: Dim,
                 module: object = None, mem: Dim = Dim(),
                 data=None, **params):
        assert_isinstance(mem, Dim)
        self.mem = mem
        self.module = module if module is not None else data
        super().__init__(name, dom, cod, data=self.module, **params)

    def __call__(self, *args, **kwargs):
        return self.module(*args, **kwargs)

    def dagger(self) -> Network:
        """ Reverse the public ports while preserving module and memory. """
        return type(self)(
            self.name, dom=self.cod, cod=self.dom, module=self.module,
            mem=self.mem, is_dagger=not self.is_dagger, z=self.z)

    def rotate(self, left=False) -> Network:
        """ Rotate the public ports while preserving module and memory. """
        del left
        return type(self)(
            self.name, dom=self.cod.r, cod=self.dom.r, module=self.module,
            mem=self.mem, is_dagger=self.is_dagger, z=(self.z + 1) % 2)

    def setoid(self):
        """ Compare given modules by identity and include private memory. """
        result = super().setoid()
        module = None if self.module is None else id(self.module)
        return result[:5] + (module, ) + result[6:] + (self.mem, )

    def to_tree(self) -> dict:
        """ Serialize the network shape, including its private memory. """
        tree = super().to_tree()
        tree['mem'] = self.mem.to_tree()
        if self.z:
            tree['z'] = self.z
        return tree

    @classmethod
    def from_tree(cls, tree: dict) -> Network:
        """ Deserialize a network, accepting trees without private memory. """
        dom, cod = map(decode, (tree['dom'], tree['cod']))
        mem = decode(tree['mem']) if 'mem' in tree else Dim()
        return cls(
            tree['name'], dom, cod, data=tree.get('data'), mem=mem,
            is_dagger='is_dagger' in tree, z=tree.get('z', 0))


class Cup(compact.Cup, Network):
    """
    A neural cup is a compact cup between self-dual dimensions, i.e. a
    network with no module since it is pure rerouting.

    Parameters:
        left (Dim) : The atomic dimension.
        right (Dim) : Its reverse.
    """


class Cap(compact.Cap, Network):
    """
    A neural cap is a compact cap between self-dual dimensions, i.e. a
    network with no module since it is pure rerouting.

    Parameters:
        left (Dim) : The atomic dimension.
        right (Dim) : Its reverse.
    """


class Swap(compact.Swap, Network):
    """
    A neural swap is a compact swap between dimensions, i.e. a network
    with no module since it is pure rerouting.

    Parameters:
        left (Dim) : The dimension on the top left and bottom right.
        right (Dim) : The dimension on the top right and bottom left.
    """


class Functor(compact.Functor):
    """
    A neural functor is a compact functor between neural diagrams.

    Parameters:
        ob (Mapping[Dim, Dim]) : Map from atomic :class:`Dim` to `cod.ob`.
        ar (Mapping[Box, Diagram]) : Map from :class:`Box` to :code:`cod`.
        cod (Category) : The codomain of the functor.
    """
    dom = cod = Diagram


Hypergraph = hypergraph.Hypergraph[Diagram]


class Para(para.Compact):
    """
    A parametric network is a network whose weights are boundary values
    rather than hidden inside its modules, i.e. a parametric map
    ``inside : dom @ param -> cod`` over :class:`Diagram`, with ``param``
    the dimension of the weights, see :mod:`discopy.para`.

    Composition and tensor accumulate the parameter spaces of the layers and
    route them to the right, so that assembling a model does not whisker
    each layer with the weights of all the others.

    Example
    -------
    >>> linear = lambda n: Para(Dim(n), Dim(n), Network(
    ...     f"linear{n}", Dim(n, n * n), Dim(n)), Dim(n * n))
    >>> network = linear(2) >> linear(2)
    >>> network.dom, network.cod, network.param
    (Dim(2), Dim(2), Dim(4, 4))
    >>> assert network.inside\\
    ...     == linear(2).inside @ Dim(4) >> linear(2).inside
    >>> assert Para.lift(Diagram.id(Dim(2))) == Para.id(Dim(2))
    """
    category = Diagram


class CMap(compact.CMap):
    """
    A neural combinatorial map is a compact map with networks as boxes,
    which computes as a graph neural network.

    The :meth:`forward` pass does synchronous message passing: one message
    per port, travelling along the wires given by the ``edges`` involution.
    :meth:`as_network` wraps the map into a :class:`Network` with a fresh
    backend module inside, which owns parameter and training state.

    :attr:`ports` lists the diagram's input ports, then each box's domain
    ports followed by its codomain ports (reversed), then the diagram's
    output ports, see :attr:`discopy.cmap.CMap.ports`.

    Example
    -------
    >>> f = Network('f', Dim(2), Dim(3, 2))
    >>> fm = f.to_map()
    >>> fm.port_dims  # f's dom, then f's dom, f's cod (reversed), f's cod
    (2, 2, 2, 3, 3, 2)
    """
    category = Diagram

    @property
    def port_dims(self) -> tuple[int, ...]:
        """ The dimension carried by each port of the map. """
        return tuple(sum(port.obj.inside) for port in self.ports)

    @cached_property
    def modules(self) -> tuple:
        """ The distinct modules of the networks inside the map. """
        modules, seen = [], set()
        for box in self.boxes:
            assert_isinstance(box, Network)
            if box.module is None:
                raise ValueError(f"{box!r} has no module.")
            if id(box.module) not in seen:
                seen.add(id(box.module))
                modules.append(box.module)
        return tuple(modules)

    @cached_property
    def module_indices(self) -> tuple[int, ...]:
        """ The unique-module index used by each box occurrence. """
        indices = {id(module): i for i, module in enumerate(self.modules)}
        return tuple(indices[id(box.module)] for box in self.boxes)

    @cached_property
    def box_ports(self) -> tuple[tuple[int, ...], ...]:
        """ The ports of each box, in domain-then-codomain order. """
        return tuple(
            indices[:len(box.dom)]
            + tuple(reversed(indices[len(box.dom):]))
            for box, indices in zip(self.boxes, self._box_port_indices))

    @property
    def memory_widths(self) -> tuple[int, ...]:
        """ The private memory width of each box occurrence. """
        return tuple(sum(box.mem.inside) for box in self.boxes)

    @property
    def input_ports(self) -> tuple[int, ...]:
        """ The indices of the boundary input ports. """
        return tuple(
            i for i, port in enumerate(self.ports)
            if port.kind == PortKind.INPUT)

    @property
    def output_ports(self) -> tuple[int, ...]:
        """ The indices of the boundary output ports. """
        return tuple(
            i for i, port in enumerate(self.ports)
            if port.kind == PortKind.OUTPUT)

    @property
    def has_boundary(self) -> bool:
        """ Whether the map has any boundary port. """
        return bool(len(self.dom) or len(self.cod))

    def as_network(
            self, name: str = "network",
            backend: str | Backend = None) -> Network:
        """
        Wrap the map back into a :class:`Network` with a fresh backend module
        inside. The wrapper registers the modules of the networks in the map,
        so that it can be trained or nested inside a larger model.

        Parameters:
            name : The name of the network.
            backend : The backend name or instance, the current backend by
                      default.
        """
        backend = get_backend(backend)
        memory_width = sum(
            sum(box.mem.inside) for box in self.boxes)
        return Network(
            name, self.dom, self.cod, module=backend.wrap(self),
            mem=Dim(memory_width))

    def forward(self, x=None, init=None,
                n_rounds: int = None, inject: bool = True,
                memory=None, return_memory: bool = False,
                causal: bool = False, backend: str | Backend = None,
                modules=None):
        """
        Apply the geometry-of-interaction :class:`Execution` of the map.

        Parameters:
            x : The input, of shape ``(batch_size, sum of domain widths)``.
            init : The initial incoming messages, given per port or as one
                   tensor of shape ``(batch_size, sum of port widths)``.
            n_rounds : The number of rounds, the number of boxes by default.
            inject : Whether to re-add ``init`` to the incoming messages at
                     every round rather than just the first.
            memory : Initial private memory, given per box occurrence or as
                     one tensor of their concatenated memory dimensions.
            return_memory : Whether to return the final per-box memories
                            together with the usual result.
            causal : Whether to activate every box once in topological order.
                     This is only valid for feed-forward maps and cannot be
                     combined with ``n_rounds``.
            backend : The backend name or instance, the current backend by
                      default.
            modules : The backend-owned modules, in :attr:`module_indices`
                      order. The modules in the boxes are used by default.

        Returns:
            The final messages at the boundary output ports, concatenated,
            or the tuple of final per-box outgoing messages in logical port
            order when the map is closed. If ``return_memory`` is true, this
            result is paired with the tuple of final per-box memories.
        """
        execution = Execution(
            self, x, init, memory, backend=backend, modules=modules)
        if causal:
            if n_rounds is not None:
                raise ValueError(
                    "A causal schedule cannot be combined with n_rounds.")
            return execution.forward_causal(inject, return_memory)
        return execution.forward(n_rounds, inject, return_memory)

    __call__ = forward


class Execution:
    """
    The geometry-of-interaction execution of a neural combinatorial map.

    Let ``edge`` be the fixpoint-free involution on ports and ``activate``
    apply every network independently. One synchronous round first activates
    the boxes, then routes their outgoing messages with
    ``incoming[i] = outgoing[edge[i]]``. Boundary inputs are emitted before
    every round, while ``init`` is optionally injected after every routing
    step as well as before the first round.

    Parameters:
        inside : The combinatorial map to execute.
        x : The boundary input.
        init : The initial incoming messages.
        memory : The initial private memory, one tensor per box occurrence.
        backend : The execution backend, the current backend by default.
        modules : The backend-owned modules, in the map's unique-module order.
                  The modules inside the boxes are used by default, so that
                  a backend can train copies of them without rebuilding
                  the map.
    """
    def __init__(
            self, inside: CMap, x=None, init=None, memory=None,
            backend: str | Backend = None, modules=None):
        assert_isinstance(inside, CMap)
        self.inside = inside
        self.x, self.init = x, init
        self.memory = memory
        self.backend = get_backend(backend)
        self.modules = inside.modules if modules is None else tuple(modules)
        if len(self.modules) != len(inside.modules):
            raise ValueError(
                f"Expected {len(inside.modules)} modules, "
                f"got {len(self.modules)}.")
        self.batch_size, self.prototype = 1, None
        self.initial = self.boundary = self.incoming = ()
        self.outgoing = self.box_outputs = ()
        self.memories = ()

    @property
    def input_ports(self) -> tuple[int, ...]:
        """ The indices of boundary input ports. """
        return self.inside.input_ports

    @property
    def output_ports(self) -> tuple[int, ...]:
        """ The indices of boundary output ports. """
        return self.inside.output_ports

    @property
    def box_ports(self) -> tuple[tuple[int, ...], ...]:
        """ The ports of each box in domain-then-codomain order. """
        return self.inside.box_ports

    @property
    def memory_widths(self) -> tuple[int, ...]:
        """ The private memory width of each box occurrence. """
        return self.inside.memory_widths

    @cached_property
    def topological_order(self) -> tuple[int, ...]:
        """ Order boxes from boundary inputs towards boundary outputs. """
        domain_owner, codomain_owner, box_port_owner = {}, {}, {}
        for box_index, (box, ports) in enumerate(zip(
                self.inside.boxes, self.box_ports)):
            arity = len(box.dom)
            for port in ports:
                box_port_owner[port] = box_index
            for port in ports[:arity]:
                domain_owner[port] = box_index
            for port in ports[arity:]:
                codomain_owner[port] = box_index

        dependencies = []
        for box_index, (box, ports) in enumerate(zip(
                self.inside.boxes, self.box_ports)):
            arity, current = len(box.dom), set()
            for port in ports[:arity]:
                source = self.inside.edges[port]
                if source in codomain_owner:
                    current.add(codomain_owner[source])
                elif source in box_port_owner:
                    raise ValueError(
                        "A causal schedule requires every box input to be "
                        "wired from a box output or boundary input.")
                elif self.inside.ports[source].kind != PortKind.INPUT:
                    raise ValueError(
                        "A causal schedule requires every box input to be "
                        "wired from a box output or boundary input.")
            dependencies.append(current)

            for port in ports[arity:]:
                target = self.inside.edges[port]
                if target in box_port_owner and target not in domain_owner:
                    raise ValueError(
                        "A causal schedule requires every box output to be "
                        "wired to a box input or boundary output.")
                if target not in box_port_owner\
                        and self.inside.ports[target].kind != PortKind.OUTPUT:
                    raise ValueError(
                        "A causal schedule requires every box output to be "
                        "wired to a box input or boundary output.")

        remaining = [set(items) for items in dependencies]
        ready = [
            box_index for box_index, items in enumerate(remaining)
            if not items]
        order = []
        while ready:
            box_index = ready.pop(0)
            order.append(box_index)
            for target, items in enumerate(remaining):
                if box_index in items:
                    items.remove(box_index)
                    if not items and target not in order\
                            and target not in ready:
                        ready.append(target)
        if len(order) != len(self.inside.boxes):
            raise ValueError(
                "A causal schedule requires an acyclic box dependency graph.")
        return tuple(order)

    def zeros(self, width: int):
        """ A zero message with the execution's batch size and prototype. """
        return self.backend.zeros(
            self.batch_size, width, like=self.prototype)

    def validate(self, value, width: int, label: str):
        """ Validate the rank, batch size and width of a message tensor. """
        shape = getattr(value, "shape", None)
        if shape is None or len(shape) != 2:
            raise ValueError(
                f"{label} must have shape (batch_size, {width}).")
        if shape[0] != self.batch_size or shape[1] != width:
            raise ValueError(
                f"{label} has shape {tuple(shape)}, expected "
                f"({self.batch_size}, {width}).")
        return value

    @staticmethod
    def _values(given):
        """ Yield non-null tensors from a tensor or per-item sequence. """
        if isinstance(given, (list, tuple)):
            return (value for value in given if value is not None)
        return iter(()) if given is None else iter((given, ))

    def _initialize_messages(self, given, widths, label):
        """ Normalize a tensor or nullable per-item sequence to messages. """
        if given is None:
            values = len(widths) * (None, )
        elif isinstance(given, (list, tuple)):
            if len(given) != len(widths):
                raise ValueError(
                    f"{label} must contain {len(widths)} messages, "
                    f"got {len(given)}.")
            values = given
        else:
            self.validate(given, sum(widths), label)
            values = self.backend.split(given, widths) if widths else ()
        return tuple(
            self.zeros(width) if value is None
            else self.validate(value, width, f"{label}[{i}]")
            for i, (value, width) in enumerate(zip(values, widths)))

    def initialize(self) -> tuple:
        """ Initialize public messages and per-box private memories. """
        widths = self.inside.port_dims
        given = (
            self._values(self.x), self._values(self.init),
            self._values(self.memory))
        reference = next((
            value for values in given for value in values), None)
        if reference is not None:
            shape = getattr(reference, "shape", None)
            if shape is None or len(shape) != 2:
                raise ValueError(
                    "Messages must have shape (batch_size, width).")
        self.batch_size = 1 if reference is None else shape[0]
        self.prototype = reference if reference is not None\
            else self.backend.prototype(self.modules)

        boundary = [self.zeros(width) for width in widths]
        if self.x is not None:
            self.validate(
                self.x, sum(widths[i] for i in self.input_ports), "x")
            slices = self.backend.split(
                self.x, tuple(widths[i] for i in self.input_ports))
            for i, message in zip(self.input_ports, slices):
                boundary[i] = message

        initial = self._initialize_messages(self.init, widths, "init")
        memories = self._initialize_messages(
            self.memory, self.memory_widths, "memory")

        incoming = list(initial)
        for i in self.input_ports:
            edge = self.inside.edges[i]
            incoming[edge] = incoming[edge] + boundary[i]

        self.initial = tuple(initial)
        self.boundary = tuple(boundary)
        self.incoming = tuple(incoming)
        self.outgoing = ()
        self.box_outputs = len(self.inside.boxes) * (None, )
        self.memories = memories
        return self.incoming

    def activate_box(self, box_index: int, incoming):
        """ Apply one network to its public messages and private memory. """
        widths = self.inside.port_dims
        ports = self.box_ports[box_index]
        public_widths = tuple(widths[i] for i in ports)
        memory_width = self.memory_widths[box_index]
        values = tuple(incoming[i] for i in ports)\
            + (self.memories[box_index], )
        module = self.modules[self.inside.module_indices[box_index]]
        output = self.backend.activate(
            module, self.backend.concatenate(values))
        self.validate(
            output, sum(public_widths) + memory_width,
            f"output of box {box_index}")
        chunks = self.backend.split(
            output, public_widths + (memory_width, ))
        public, next_memory = chunks[:-1], chunks[-1]
        box_output = (
            self.backend.concatenate(public) if public else self.zeros(0))
        return public, next_memory, box_output

    def activate(self) -> tuple:
        """ Apply each network to its public messages and private memory. """
        widths = self.inside.port_dims
        outgoing = [self.zeros(width) for width in widths]
        for i in self.input_ports:
            outgoing[i] = self.boundary[i]

        box_outputs, memories = [], []
        for box_index, ports in enumerate(self.box_ports):
            public, next_memory, box_output = self.activate_box(
                box_index, self.incoming)
            box_outputs.append(box_output)
            memories.append(next_memory)
            for i, chunk in zip(ports, public):
                outgoing[i] = chunk

        self.outgoing = tuple(outgoing)
        self.box_outputs = tuple(box_outputs)
        self.memories = tuple(memories)
        return self.outgoing

    def route(self) -> tuple:
        """ Route outgoing messages along the edge involution. """
        self.incoming = tuple(
            self.outgoing[self.inside.edges[i]]
            for i in range(self.inside.n_ports))
        return self.incoming

    def inject(self) -> tuple:
        """ Add the initial messages to the current incoming messages. """
        self.incoming = tuple(
            message + initial
            for message, initial in zip(self.incoming, self.initial))
        return self.incoming

    def readout(self):
        """ Read boundary outputs, or final box outputs for a closed map. """
        if self.inside.has_boundary:
            return self.backend.concatenate(tuple(
                self.incoming[i] for i in self.output_ports))\
                if self.output_ports else self.zeros(0)
        return self.box_outputs

    def forward(
            self, n_rounds: int = None, inject: bool = True,
            return_memory: bool = False):
        """ Execute synchronous activation and routing rounds. """
        self.initialize()
        n_rounds = len(self.inside.boxes) if n_rounds is None else n_rounds
        if n_rounds < 0:
            raise ValueError("n_rounds cannot be negative.")
        for _ in range(n_rounds):
            self.activate()
            self.route()
            if inject and self.init is not None:
                self.inject()
        result = self.readout()
        return (result, self.memories) if return_memory else result

    def forward_causal(
            self, inject: bool = True, return_memory: bool = False):
        """ Execute every box once in topological order. """
        self.initialize()
        widths = self.inside.port_dims
        incoming = list(self.incoming)
        outgoing = [self.zeros(width) for width in widths]
        for port in self.input_ports:
            outgoing[port] = self.boundary[port]
        box_outputs = list(self.box_outputs)
        memories = list(self.memories)

        for box_index in self.topological_order:
            ports = self.box_ports[box_index]
            public, next_memory, box_output = self.activate_box(
                box_index, incoming)
            box_outputs[box_index] = box_output
            memories[box_index] = next_memory
            for port, chunk in zip(ports, public):
                outgoing[port] = chunk
                target = self.inside.edges[port]
                incoming[target] = chunk + self.initial[target]\
                    if inject and self.init is not None else chunk

        self.incoming, self.outgoing = tuple(incoming), tuple(outgoing)
        self.box_outputs, self.memories = (
            tuple(box_outputs), tuple(memories))
        result = self.readout()
        return (result, self.memories) if return_memory else result

    __call__ = forward


Id = Diagram.id

Diagram.braid_factory = Swap
Diagram.functor_factory = Functor
Diagram.map_factory = CMap
Diagram.cup_factory, Diagram.cap_factory = Cup, Cap


class Equation(compact.Equation):
    """ An equation between neural diagrams, compared up to maps. """
    up_to = staticmethod(Diagram.to_map)
