name: build

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  SRC_DIR: discopy
  TEST_DIR: test
  DOCS_DIR: docs

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install linter
      run:
        python -m pip install pyproject-flake8 coverage pylint
    - name: Check for errors
      run:
        # stop the build if there are Python syntax errors or undefined names
        pflake8 discopy
    - name: pylint
      run:
        pylint discopy
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # caching pip dependencies
    - name: Install
      run: |
        pip install coverage pytest
        pip install torch --index-url https://download.pytorch.org/whl/cpu  # Install PyTorch without CUDA
        pip install .[test]
    - name: Test
      run:
        coverage run -m pytest
    - name: Coverage
      run:
        coverage report --fail-under=99 --show-missing
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # caching pip dependencies
    - name: Check for changes in source files
      run: |
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '${{ env.SRC_DIR }}/|${{ env.DOCS_DIR }}' || true)
        if [ -z "$changed_files" ]; then
          echo "No changes in source files. Cancelling the job."
          exit 0
        else
          echo "Changes detected in source files. Continuing with the job."
        fi
    - name: Install Pandoc on Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    - name: Install
      run: |
        sudo apt-get install -y pandoc
        pip install .[docs]
    - name: Build
      run: |
        sphinx-build ${{ env.DOCS_DIR }} ${{ env.DOCS_DIR }}/_build/html
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: docs
        path: ${{ env.DOCS_DIR }}/_build/html

